/*
 * moon_testmap.h — Loader for the "Test" multi-image container file.
 *
 * The Moonstone "Test" file (198745 bytes) is a container of 9 sequential
 * Mindscape-PIV images.  No explicit index table is present; images are
 * laid out back-to-back, each starting with the standard 2-byte plane-count
 * magic word (0x0004 or 0x0005).
 *
 * Image index → content (from mog.asm analysis):
 *   0  — unknown background
 *   1  — unknown background
 *   2  — unknown background
 *   3  — unknown background
 *   4  — unknown background
 *   5  — unknown background
 *   6  — unknown background
 *   7  — unknown background
 *   8  — overworld map (320×200, 5 bitplanes)
 *
 * Usage example (load overworld map via file):
 *   MoonPiv *map = moon_testmap_load_piv("Test", 8);
 *
 * Usage example (load from an embedded byte array generated by bin2h.py):
 *   #include "test_map.h"   // generated header
 *   MoonPiv *map = moon_testmap_load_piv_from_buffer(test_map_data,
 *                                                    test_map_size, 8);
 */

#ifndef MOON_TESTMAP_H
#define MOON_TESTMAP_H

#include "moon_assets.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * moon_testmap_load_piv - Load a single PIV image from the "Test" container.
 *
 * @name:      filename of the container (usually "Test"), resolved relative
 *             to the asset directory passed to moon_init().
 * @img_index: zero-based index of the image to extract (0–8).
 *             Use 8 for the overworld map background.
 *
 * Returns a newly allocated MoonPiv on success, or NULL on error.
 * The caller is responsible for freeing it with moon_piv_free().
 */
MoonPiv *moon_testmap_load_piv(const char *name, int img_index);

/**
 * moon_testmap_load_piv_from_buffer - Extract a PIV image from an
 * already-loaded byte array (e.g. generated by tools/bin2h.py).
 *
 * @data:      pointer to the raw "Test" file bytes.
 * @len:       total number of bytes in the buffer.
 * @img_index: zero-based index of the image to extract (0–8).
 *
 * Returns a newly allocated MoonPiv on success, or NULL on error.
 * The caller is responsible for freeing it with moon_piv_free().
 */
MoonPiv *moon_testmap_load_piv_from_buffer(const uint8_t *data, size_t len,
                                           int img_index);

#ifdef __cplusplus
}
#endif

#endif /* MOON_TESTMAP_H */
