/*
 * moon_anim_lab0979.c — IMAGEXCEL animation script "lab0979".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:17143
 * (LAB_0979).  30 bytes, 3 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0979 — 30 bytes, 3 step(s) */
static const uint8_t lab0979_script[] = {
    IX_DRAW(0), 0x00, 0x9D, 0x00, 0xFF, 0x61,  /* frame=0 y=-99 x=-159 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(0), 0x01, 0x9D, 0x00, 0xFF, 0x61,  /* frame=1 y=-99 x=-159 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(0), 0x02, 0x9F, 0x00, 0xFF, 0x61,  /* frame=2 y=-97 x=-159 */
    IX_STEP_SCRIPT_END,  /* end of step 3 */
}; /* lab0979_script */
