/*
 * moon_anim_lab08bc.c — IMAGEXCEL animation script "lab08bc".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:16168
 * (LAB_08BC).  138 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08BC — 138 bytes, 1 step(s) */
static const uint8_t lab08bc_script[] = {
    0xA4, 0x3F, 0x08, 0x0B,
    0xEC, 0x00,
    IX_DRAW(0), 0x24, 0x08, 0x0C, 0xFD, 0x00,  /* frame=36 y=+8 x=-768 */
    IX_DRAW(0), 0x4D, 0x08, 0x0D, 0x07, 0x00,  /* frame=77 y=+8 x=+1792 */
    IX_DRAW(0), 0x68, 0x08, 0x0E, 0x13, 0x00,  /* frame=104 y=+8 x=+4864 */
    IX_DRAW(0), 0x87, 0x00, 0x3C, 0xF3, 0x00,  /* frame=135 y=+0 x=-3328 */
    IX_DRAW(0), 0x87, 0x08, 0x0F, 0x14, 0x00,  /* frame=135 y=+8 x=+5120 */
    IX_DRAW(0), 0x91, 0x00, 0x12, 0xD4, 0x00,  /* frame=145 y=+0 x=-11264 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab08bc_script */
