/*
 * moon_anim_lab087b.c — IMAGEXCEL animation script "lab087b".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15366
 * (LAB_087B).  56 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_087B — 56 bytes, 1 step(s) */
static const uint8_t lab087b_script[] = {
    IX_DRAW(1), 0x01, 0x0C, 0x01, 0xFF, 0x80,  /* frame=1 y=+12 x=-128 */
    IX_DRAW(1), 0x01, 0xFD, 0x00, 0xFF, 0x98,  /* frame=1 y=-3 x=-104 */
    IX_DRAW(1), 0x02, 0xEE, 0x00, 0xFF, 0xB4,  /* frame=2 y=-18 x=-76 */
    IX_DRAW(1), 0x03, 0xE4, 0x00, 0xFF, 0xD2,  /* frame=3 y=-28 x=-46 */
    IX_DRAW(1), 0x04, 0xE9, 0x00, 0xFF, 0xE8,  /* frame=4 y=-23 x=-24 */
    IX_DRAW(0), 0x07, 0xFB, 0x01, 0xFF, 0xC8,  /* frame=7 y=-5 x=-56 */
    IX_DRAW(0), 0x08, 0x1C, 0x00, 0xFF, 0xE6,  /* frame=8 y=+28 x=-26 */
    IX_DRAW(1), 0x10, 0x08, 0x01, 0x00, 0x12,  /* frame=16 y=+8 x=+18 */
    IX_DRAW(1), 0x0E, 0x01, 0x00, 0x00, 0x12,  /* frame=14 y=+1 x=+18 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab087b_script */
