/*
 * moon_anim_lab00e5.c — IMAGEXCEL animation script "lab00e5".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2372
 * (LAB_00E5).  150 bytes, 15 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00E5 — 150 bytes, 15 step(s) */
static const uint8_t lab00e5_script[] = {
    0x88, 0x08,
    IX_DRAW(4), 0x02, 0x5D, 0x00, 0xFF, 0xE3,  /* frame=2 y=+93 x=-29 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(4), 0x01, 0x57, 0x00, 0xFF, 0xE4,  /* frame=1 y=+87 x=-28 */
    IX_STEP_NEXT,  /* end of step 2 */
    IX_DRAW(4), 0x02, 0x55, 0x00, 0xFF, 0xE4,  /* frame=2 y=+85 x=-28 */
    IX_STEP_NEXT,  /* end of step 3 */
    IX_DRAW(4), 0x00, 0x4E, 0x00, 0xFF, 0xE4,  /* frame=0 y=+78 x=-28 */
    IX_STEP_NEXT,  /* end of step 4 */
    IX_DRAW(4), 0x02, 0x4A, 0x00, 0xFF, 0xE4,  /* frame=2 y=+74 x=-28 */
    IX_STEP_NEXT,  /* end of step 5 */
    IX_DRAW(4), 0x01, 0x42, 0x00, 0xFF, 0xE4,  /* frame=1 y=+66 x=-28 */
    IX_STEP_NEXT,  /* end of step 6 */
    IX_DRAW(4), 0x02, 0x3D, 0x00, 0xFF, 0xE4,  /* frame=2 y=+61 x=-28 */
    IX_STEP_NEXT,  /* end of step 7 */
    IX_DRAW(4), 0x00, 0x35, 0x00, 0xFF, 0xE4,  /* frame=0 y=+53 x=-28 */
    IX_STEP_NEXT,  /* end of step 8 */
    IX_DRAW(4), 0x02, 0x30, 0x00, 0xFF, 0xE4,  /* frame=2 y=+48 x=-28 */
    IX_STEP_NEXT,  /* end of step 9 */
    IX_DRAW(4), 0x01, 0x27, 0x00, 0xFF, 0xE4,  /* frame=1 y=+39 x=-28 */
    IX_STEP_NEXT,  /* end of step 10 */
    IX_DRAW(4), 0x02, 0x22, 0x00, 0xFF, 0xE4,  /* frame=2 y=+34 x=-28 */
    IX_STEP_NEXT,  /* end of step 11 */
    IX_DRAW(4), 0x00, 0x19, 0x00, 0xFF, 0xE4,  /* frame=0 y=+25 x=-28 */
    IX_STEP_NEXT,  /* end of step 12 */
    IX_DRAW(4), 0x02, 0x12, 0x00, 0xFF, 0xE4,  /* frame=2 y=+18 x=-28 */
    IX_STEP_NEXT,  /* end of step 13 */
    IX_DRAW(4), 0x01, 0x0A, 0x00, 0xFF, 0xE4,  /* frame=1 y=+10 x=-28 */
    IX_STEP_NEXT,  /* end of step 14 */
    0x88, 0x0A,
    IX_DRAW(4), 0x02, 0x04, 0x10, 0xFF, 0xE4,  /* frame=2 y=+4 x=-28 */
    IX_STEP_SCRIPT_END,  /* end of step 15 */
}; /* lab00e5_script */
