/*
 * moon_anim_lab00ec.c — IMAGEXCEL animation script "lab00ec".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2519
 * (LAB_00EC).  118 bytes, 14 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00EC — 118 bytes, 14 step(s) */
static const uint8_t lab00ec_script[] = {
    IX_DRAW(5), 0x29, 0xE9, 0x20, 0xFF, 0xF3,  /* frame=41 y=-23 x=-13 */
    IX_DRAW(5), 0x28, 0x02, 0x20, 0xFF, 0xE7,  /* frame=40 y=+2 x=-25 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(5), 0x2A, 0xE1, 0x20, 0xFF, 0xE8,  /* frame=42 y=-31 x=-24 */
    IX_STEP_NEXT,  /* end of step 2 */
    IX_DRAW(5), 0x2B, 0xDD, 0x20, 0xFF, 0xEA,  /* frame=43 y=-35 x=-22 */
    IX_STEP_NEXT,  /* end of step 3 */
    IX_DRAW(5), 0x2C, 0xDB, 0x20, 0xFF, 0xEC,  /* frame=44 y=-37 x=-20 */
    IX_STEP_NEXT,  /* end of step 4 */
    IX_DRAW(5), 0x2D, 0xDA, 0x20, 0xFF, 0xEE,  /* frame=45 y=-38 x=-18 */
    IX_STEP_NEXT,  /* end of step 5 */
    IX_DRAW(5), 0x2E, 0xD8, 0x20, 0xFF, 0xEE,  /* frame=46 y=-40 x=-18 */
    IX_STEP_NEXT,  /* end of step 6 */
    IX_DRAW(5), 0x2F, 0xD6, 0x20, 0xFF, 0xEF,  /* frame=47 y=-42 x=-17 */
    IX_STEP_NEXT,  /* end of step 7 */
    IX_DRAW(5), 0x30, 0xD4, 0x20, 0xFF, 0xEF,  /* frame=48 y=-44 x=-17 */
    IX_STEP_NEXT,  /* end of step 8 */
    IX_DRAW(5), 0x31, 0xD2, 0x20, 0xFF, 0xF0,  /* frame=49 y=-46 x=-16 */
    IX_STEP_NEXT,  /* end of step 9 */
    IX_DRAW(5), 0x32, 0xD2, 0x20, 0xFF, 0xF1,  /* frame=50 y=-46 x=-15 */
    IX_STEP_NEXT,  /* end of step 10 */
    IX_DRAW(5), 0x33, 0xD1, 0x20, 0xFF, 0xF2,  /* frame=51 y=-47 x=-14 */
    IX_STEP_NEXT,  /* end of step 11 */
    IX_DRAW(5), 0x34, 0xD1, 0x20, 0xFF, 0xF2,  /* frame=52 y=-47 x=-14 */
    IX_STEP_NEXT,  /* end of step 12 */
    IX_DRAW(5), 0x35, 0xD0, 0x20, 0xFF, 0xF3,  /* frame=53 y=-48 x=-13 */
    IX_STEP_NEXT,  /* end of step 13 */
    IX_DRAW(5), 0x36, 0xCE, 0x20, 0xFF, 0xF6,  /* frame=54 y=-50 x=-10 */
    IX_STEP_SCRIPT_END,  /* end of step 14 */
}; /* lab00ec_script */
