/*
 * moon_anim_lab0876.c — IMAGEXCEL animation script "lab0876".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15338
 * (LAB_0876).  50 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0876 — 50 bytes, 1 step(s) */
static const uint8_t lab0876_script[] = {
    IX_DRAW(1), 0x00, 0x0F, 0x00, 0xFF, 0x80,  /* frame=0 y=+15 x=-128 */
    IX_DRAW(1), 0x00, 0xFB, 0x01, 0xFF, 0x96,  /* frame=0 y=-5 x=-106 */
    IX_DRAW(1), 0x01, 0xE7, 0x01, 0xFF, 0xAF,  /* frame=1 y=-25 x=-81 */
    IX_DRAW(1), 0x03, 0xD8, 0x00, 0xFF, 0xD0,  /* frame=3 y=-40 x=-48 */
    IX_DRAW(1), 0x05, 0xE2, 0x01, 0xFF, 0xE2,  /* frame=5 y=-30 x=-30 */
    IX_DRAW(0), 0x0F, 0xDF, 0x00, 0xFF, 0xFD,  /* frame=15 y=-33 x=-3 */
    IX_DRAW(0), 0x0E, 0xC4, 0x00, 0xFF, 0xD2,  /* frame=14 y=-60 x=-46 */
    IX_DRAW(0), 0x15, 0x14, 0x01, 0xFF, 0xFD,  /* frame=21 y=+20 x=-3 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0876_script */
