/*
 * moon_anim_anim_015e.c — IMAGEXCEL animation script "anim_015e".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14809
 * (LAB_083D).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_083D — 20 bytes, 1 step(s) */
static const uint8_t anim_015e_script[] = {
    IX_DRAW(0), 0x01, 0x07, 0x03, 0xFF, 0xD4,  /* frame=1 y=+7 x=-44 */
    IX_DRAW(0), 0x02, 0x06, 0x03, 0x00, 0x12,  /* frame=2 y=+6 x=+18 */
    IX_DRAW(0), 0x10, 0x16, 0x00, 0xFF, 0xBD,  /* frame=16 y=+22 x=-67 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* anim_015e_script */
