/*
 * moon_anim_lab0800.c — IMAGEXCEL animation script "lab0800".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14316
 * (LAB_0800).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0800 — 20 bytes, 1 step(s) */
static const uint8_t lab0800_script[] = {
    IX_DRAW(0), 0x00, 0x04, 0x01, 0xFF, 0xE6,  /* frame=0 y=+4 x=-26 */
    IX_DRAW(0), 0x01, 0x1E, 0x41, 0x00, 0x0B,  /* frame=1 y=+30 x=+11 */
    IX_DRAW(1), 0x37, 0xF4, 0x00, 0xFF, 0xF2,  /* frame=55 y=-12 x=-14 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0800_script */
