/*
 * moon_anim_lab081a.c — IMAGEXCEL animation script "lab081a".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14568
 * (LAB_081A).  28 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_081A — 28 bytes, 1 step(s) */
static const uint8_t lab081a_script[] = {
    0xD0, 0x00, 0x04, 0x35, 0x32, 0x40, 0xFF, 0xF2,
    IX_DRAW(1), 0x33, 0x1A, 0x01, 0xFF, 0xFE,  /* frame=51 y=+26 x=-2 */
    IX_DRAW(1), 0x32, 0x01, 0x01, 0xFF, 0xF1,  /* frame=50 y=+1 x=-15 */
    IX_DRAW(1), 0x34, 0x19, 0x40, 0x00, 0x24,  /* frame=52 y=+25 x=+36 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab081a_script */
