/*
 * moon_anim_lab0898.c — IMAGEXCEL animation script "lab0898".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15756
 * (LAB_0898).  76 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0898 — 76 bytes, 1 step(s) */
static const uint8_t lab0898_script[] = {
    0x88, 0x04,
    IX_DRAW(0), 0x0D, 0xED, 0x01, 0xFF, 0xDE,  /* frame=13 y=-19 x=-34 */
    IX_DRAW(0), 0x0E, 0xDE, 0x01, 0xFF, 0xE0,  /* frame=14 y=-34 x=-32 */
    IX_DRAW(0), 0x0F, 0xD0, 0x00, 0xFF, 0xE0,  /* frame=15 y=-48 x=-32 */
    IX_DRAW(0), 0x0C, 0x11, 0x01, 0xFF, 0xEB,  /* frame=12 y=+17 x=-21 */
    IX_DRAW(0), 0x1A, 0x29, 0x41, 0xFF, 0xD8,  /* frame=26 y=+41 x=-40 */
    IX_DRAW(0), 0x19, 0x2D, 0x40, 0x00, 0x20,  /* frame=25 y=+45 x=+32 */
    IX_DRAW(0), 0x18, 0x31, 0x40, 0xFF, 0xCA,  /* frame=24 y=+49 x=-54 */
    IX_DRAW(0), 0x14, 0x04, 0x40, 0x00, 0x1A,  /* frame=20 y=+4 x=+26 */
    IX_DRAW(0), 0x13, 0xD6, 0x40, 0x00, 0x17,  /* frame=19 y=-42 x=+23 */
    IX_DRAW(0), 0x12, 0x05, 0x40, 0xFF, 0xCF,  /* frame=18 y=+5 x=-49 */
    IX_DRAW(0), 0x11, 0x19, 0x40, 0xFF, 0xDA,  /* frame=17 y=+25 x=-38 */
    IX_DRAW(0), 0x11, 0xCC, 0x40, 0xFF, 0xD5,  /* frame=17 y=-52 x=-43 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0898_script */
