/*
 * moon_anim_lab082d.c — IMAGEXCEL animation script "lab082d".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14697
 * (LAB_082D).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_082D — 20 bytes, 1 step(s) */
static const uint8_t lab082d_script[] = {
    IX_DRAW(0), 0x1B, 0x00, 0x01, 0xFF, 0xEF,  /* frame=27 y=+0 x=-17 */
    IX_DRAW(0), 0x1C, 0x21, 0x01, 0xFF, 0xE2,  /* frame=28 y=+33 x=-30 */
    IX_DRAW(1), 0x4A, 0xFC, 0x00, 0xFF, 0xFE,  /* frame=74 y=-4 x=-2 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab082d_script */
