/*
 * moon_anim_lab0887.c — IMAGEXCEL animation script "lab0887".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15501
 * (LAB_0887).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0887 — 14 bytes, 1 step(s) */
static const uint8_t lab0887_script[] = {
    IX_DRAW(1), 0x0B, 0x06, 0x00, 0xFF, 0xE2,  /* frame=11 y=+6 x=-30 */
    IX_DRAW(1), 0x0C, 0x12, 0x00, 0x00, 0x11,  /* frame=12 y=+18 x=+17 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0887_script */
