/*
 * moon_anim_lab089d.c — IMAGEXCEL animation script "lab089d".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15780
 * (LAB_089D).  22 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_089D — 22 bytes, 1 step(s) */
static const uint8_t lab089d_script[] = {
    0x88, 0x02,
    IX_DRAW(0), 0x29, 0xF6, 0x01, 0xFF, 0xE2,  /* frame=41 y=-10 x=-30 */
    IX_DRAW(0), 0x28, 0x2C, 0x41, 0xFF, 0xD0,  /* frame=40 y=+44 x=-48 */
    IX_DRAW(0), 0x27, 0x38, 0x40, 0xFF, 0xF8,  /* frame=39 y=+56 x=-8 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab089d_script */
