/*
 * moon_anim_lab08a3.c — IMAGEXCEL animation script "lab08a3".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15880
 * (LAB_08A3).  42 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08A3 — 42 bytes, 1 step(s) */
static const uint8_t lab08a3_script[] = {
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0xA4, 0x51,  /* frame=0 y=+0 x=-23471 */
    0x88, 0x03,
    0xB4, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(1), 0x33, 0xF0, 0x20, 0xFF, 0xDC,  /* frame=51 y=-16 x=-36 */
    IX_DRAW(1), 0x32, 0x06, 0x20, 0xFF, 0xDC,  /* frame=50 y=+6 x=-36 */
    IX_DRAW(1), 0x31, 0x1F, 0x20, 0xFF, 0xE3,  /* frame=49 y=+31 x=-29 */
    IX_DRAW(1), 0x30, 0x2A, 0x60, 0xFF, 0xCD,  /* frame=48 y=+42 x=-51 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab08a3_script */
