/*
 * moon_anim_lab097a.c — IMAGEXCEL animation script "lab097a".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:17148
 * (LAB_097A).  50 bytes, 3 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_097A — 50 bytes, 3 step(s) */
static const uint8_t lab097a_script[] = {
    IX_DRAW(0), 0x0F, 0x29, 0x00, 0x00, 0x5D,  /* frame=15 y=+41 x=+93 */
    IX_DRAW(0), 0x10, 0x5C, 0x00, 0x00, 0x36,  /* frame=16 y=+92 x=+54 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(0), 0x11, 0x29, 0x00, 0x00, 0x5C,  /* frame=17 y=+41 x=+92 */
    IX_DRAW(0), 0x12, 0x5B, 0x00, 0x00, 0x2B,  /* frame=18 y=+91 x=+43 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(0), 0x13, 0x29, 0x00, 0x00, 0x59,  /* frame=19 y=+41 x=+89 */
    IX_DRAW(0), 0x14, 0x5A, 0x00, 0x00, 0x2A,  /* frame=20 y=+90 x=+42 */
    IX_STEP_SCRIPT_END,  /* end of step 3 */
}; /* lab097a_script */
