/*
 * moon_anim_lab082b.c — IMAGEXCEL animation script "lab082b".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14691
 * (LAB_082B).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_082B — 14 bytes, 1 step(s) */
static const uint8_t lab082b_script[] = {
    IX_DRAW(0), 0x19, 0x00, 0x01, 0xFF, 0xEF,  /* frame=25 y=+0 x=-17 */
    IX_DRAW(1), 0x4A, 0xFA, 0x01, 0xFF, 0xFF,  /* frame=74 y=-6 x=-1 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab082b_script */
