/*
 * moon_anim_lab07db.c — IMAGEXCEL animation script "lab07db".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13972
 * (LAB_07DB).  28 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07DB — 28 bytes, 1 step(s) */
static const uint8_t lab07db_script[] = {
    IX_DRAW(0), 0x01, 0x2D, 0x01, 0xFF, 0xF3,  /* frame=1 y=+45 x=-13 */
    IX_DRAW(0), 0x00, 0xF7, 0x01, 0xFF, 0xF7,  /* frame=0 y=-9 x=-9 */
    IX_DRAW(3), 0x01, 0xFA, 0x01, 0x00, 0x04,  /* frame=1 y=-6 x=+4 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07db_script */
