/*
 * moon_anim_lab07e6.c — IMAGEXCEL animation script "lab07e6".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14006
 * (LAB_07E6).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E6 — 14 bytes, 1 step(s) */
static const uint8_t lab07e6_script[] = {
    IX_DRAW(0), 0x0F, 0xF9, 0x01, 0xFF, 0xF6,  /* frame=15 y=-7 x=-10 */
    IX_DRAW(3), 0x00, 0xF2, 0x00, 0xFF, 0xFE,  /* frame=0 y=-14 x=-2 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e6_script */
