/*
 * moon_anim_lab07e2.c — IMAGEXCEL animation script "lab07e2".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13994
 * (LAB_07E2).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E2 — 14 bytes, 1 step(s) */
static const uint8_t lab07e2_script[] = {
    IX_DRAW(3), 0x00, 0xEC, 0x00, 0x00, 0x03,  /* frame=0 y=-20 x=+3 */
    IX_DRAW(0), 0x0B, 0xF6, 0x01, 0xFF, 0xF7,  /* frame=11 y=-10 x=-9 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e2_script */
