/*
 * moon_anim_lab0870.c — IMAGEXCEL animation script "lab0870".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15246
 * (LAB_0870).  26 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0870 — 26 bytes, 1 step(s) */
static const uint8_t lab0870_script[] = {
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(0), 0x3F, 0xF2, 0x00, 0xFF, 0xE9,  /* frame=63 y=-14 x=-23 */
    IX_DRAW(0), 0x3F, 0xF5, 0x00, 0xFF, 0xFB,  /* frame=63 y=-11 x=-5 */
    IX_DRAW(0), 0x3F, 0xEE, 0x00, 0x00, 0x0D,  /* frame=63 y=-18 x=+13 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0870_script */
