/*
 * moon_anim_lab08a7.c — IMAGEXCEL animation script "lab08a7".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15907
 * (LAB_08A7).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08A7 — 20 bytes, 1 step(s) */
static const uint8_t lab08a7_script[] = {
    IX_DRAW(0), 0x03, 0xFC, 0x01, 0xFF, 0xE5,  /* frame=3 y=-4 x=-27 */
    IX_DRAW(0), 0x00, 0xD3, 0x01, 0xFF, 0xED,  /* frame=0 y=-45 x=-19 */
    IX_DRAW(0), 0x01, 0xFD, 0x00, 0x00, 0x0E,  /* frame=1 y=-3 x=+14 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab08a7_script */
