/*
 * moon_anim_lab00e3.c — IMAGEXCEL animation script "lab00e3".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2351
 * (LAB_00E3).  256 bytes, 31 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00E3 — 256 bytes, 31 step(s) */
static const uint8_t lab00e3_script[] = {
    IX_DRAW(4), 0x1B, 0x5F, 0x00, 0xFF, 0xE4,  /* frame=27 y=+95 x=-28 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(4), 0x1B, 0x59, 0x00, 0xFF, 0xE4,  /* frame=27 y=+89 x=-28 */
    IX_STEP_NEXT,  /* end of step 2 */
    IX_DRAW(4), 0x1B, 0x54, 0x00, 0xFF, 0xE4,  /* frame=27 y=+84 x=-28 */
    IX_STEP_NEXT,  /* end of step 3 */
    IX_DRAW(4), 0x1B, 0x4F, 0x00, 0xFF, 0xE4,  /* frame=27 y=+79 x=-28 */
    IX_STEP_NEXT,  /* end of step 4 */
    IX_DRAW(4), 0x1B, 0x4A, 0x00, 0xFF, 0xE4,  /* frame=27 y=+74 x=-28 */
    IX_STEP_NEXT,  /* end of step 5 */
    IX_DRAW(4), 0x1B, 0x45, 0x00, 0xFF, 0xE4,  /* frame=27 y=+69 x=-28 */
    IX_STEP_NEXT,  /* end of step 6 */
    IX_DRAW(4), 0x1B, 0x40, 0x00, 0xFF, 0xE4,  /* frame=27 y=+64 x=-28 */
    IX_STEP_NEXT,  /* end of step 7 */
    IX_DRAW(4), 0x1B, 0x3B, 0x00, 0xFF, 0xE4,  /* frame=27 y=+59 x=-28 */
    IX_STEP_NEXT,  /* end of step 8 */
    IX_DRAW(4), 0x1B, 0x36, 0x00, 0xFF, 0xE4,  /* frame=27 y=+54 x=-28 */
    IX_STEP_NEXT,  /* end of step 9 */
    IX_DRAW(4), 0x1B, 0x31, 0x00, 0xFF, 0xE4,  /* frame=27 y=+49 x=-28 */
    IX_STEP_NEXT,  /* end of step 10 */
    IX_DRAW(4), 0x1B, 0x2C, 0x00, 0xFF, 0xE4,  /* frame=27 y=+44 x=-28 */
    IX_STEP_NEXT,  /* end of step 11 */
    IX_DRAW(4), 0x1B, 0x27, 0x00, 0xFF, 0xE4,  /* frame=27 y=+39 x=-28 */
    IX_STEP_NEXT,  /* end of step 12 */
    IX_DRAW(4), 0x1B, 0x22, 0x00, 0xFF, 0xE4,  /* frame=27 y=+34 x=-28 */
    IX_STEP_NEXT,  /* end of step 13 */
    IX_DRAW(4), 0x1B, 0x1D, 0x00, 0xFF, 0xE4,  /* frame=27 y=+29 x=-28 */
    IX_DRAW(4), 0x1B, 0x1D, 0x00, 0xFF, 0xE4,  /* frame=27 y=+29 x=-28 */
    IX_STEP_NEXT,  /* end of step 14 */
    IX_DRAW(4), 0x1B, 0x18, 0x00, 0xFF, 0xE4,  /* frame=27 y=+24 x=-28 */
    IX_STEP_NEXT,  /* end of step 15 */
    IX_DRAW(4), 0x1B, 0x13, 0x00, 0xFF, 0xE4,  /* frame=27 y=+19 x=-28 */
    IX_STEP_NEXT,  /* end of step 16 */
    IX_DRAW(4), 0x1B, 0x0E, 0x00, 0xFF, 0xE4,  /* frame=27 y=+14 x=-28 */
    IX_STEP_NEXT,  /* end of step 17 */
    IX_DRAW(4), 0x1B, 0x09, 0x00, 0xFF, 0xE4,  /* frame=27 y=+9 x=-28 */
    IX_STEP_NEXT,  /* end of step 18 */
    IX_DRAW(4), 0x1B, 0x04, 0x00, 0xFF, 0xE4,  /* frame=27 y=+4 x=-28 */
    IX_STEP_NEXT,  /* end of step 19 */
    IX_DRAW(4), 0x1B, 0xFF, 0x00, 0xFF, 0xE4,  /* frame=27 y=-1 x=-28 */
    IX_STEP_NEXT,  /* end of step 20 */
    IX_DRAW(4), 0x1B, 0xFC, 0x00, 0xFF, 0xE4,  /* frame=27 y=-4 x=-28 */
    IX_STEP_NEXT,  /* end of step 21 */
    IX_DRAW(4), 0x1B, 0xF7, 0x00, 0xFF, 0xE4,  /* frame=27 y=-9 x=-28 */
    IX_STEP_NEXT,  /* end of step 22 */
    IX_DRAW(4), 0x1B, 0xF2, 0x00, 0xFF, 0xE4,  /* frame=27 y=-14 x=-28 */
    IX_STEP_NEXT,  /* end of step 23 */
    IX_DRAW(4), 0x1C, 0xF1, 0x00, 0xFF, 0xE4,  /* frame=28 y=-15 x=-28 */
    IX_STEP_NEXT,  /* end of step 24 */
    IX_DRAW(4), 0x1D, 0xF1, 0x00, 0xFF, 0xE5,  /* frame=29 y=-15 x=-27 */
    IX_STEP_NEXT,  /* end of step 25 */
    IX_DRAW(4), 0x1E, 0xF0, 0x00, 0xFF, 0xE6,  /* frame=30 y=-16 x=-26 */
    IX_STEP_NEXT,  /* end of step 26 */
    IX_DRAW(4), 0x1F, 0xF0, 0x00, 0xFF, 0xE7,  /* frame=31 y=-16 x=-25 */
    IX_STEP_NEXT,  /* end of step 27 */
    IX_DRAW(4), 0x20, 0xF0, 0x00, 0xFF, 0xE5,  /* frame=32 y=-16 x=-27 */
    IX_STEP_NEXT,  /* end of step 28 */
    IX_DRAW(4), 0x21, 0xF1, 0x00, 0xFF, 0xE5,  /* frame=33 y=-15 x=-27 */
    IX_STEP_NEXT,  /* end of step 29 */
    IX_DRAW(4), 0x22, 0xF1, 0x00, 0xFF, 0xE4,  /* frame=34 y=-15 x=-28 */
    IX_STEP_NEXT,  /* end of step 30 */
    0x88, 0x08,
    IX_DRAW(4), 0x23, 0xF2, 0x00, 0xFF, 0xE4,  /* frame=35 y=-14 x=-28 */
    IX_STEP_SCRIPT_END,  /* end of step 31 */
}; /* lab00e3_script */
