/*
 * moon_anim_lab0890.c — IMAGEXCEL animation script "lab0890".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15545
 * (LAB_0890).  130 bytes, 4 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0890 — 130 bytes, 4 step(s) */
static const uint8_t lab0890_script[] = {
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0x88, 0x03,  /* frame=0 y=+0 x=-30717 */
    IX_DRAW(0), 0x24, 0x2A, 0x00, 0xFF, 0xE0,  /* frame=36 y=+42 x=-32 */
    IX_DRAW(0), 0x23, 0x12, 0x01, 0xFF, 0xE7,  /* frame=35 y=+18 x=-25 */
    IX_DRAW(0), 0x22, 0xEC, 0x01, 0xFF, 0xE4,  /* frame=34 y=-20 x=-28 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    IX_DRAW(0), 0x06, 0x0E, 0x01, 0xFF, 0xDE,  /* frame=6 y=+14 x=-34 */
    IX_DRAW(0), 0x0F, 0x02, 0x42, 0x00, 0x1A,  /* frame=15 y=+2 x=+26 */
    IX_DRAW(0), 0x05, 0xEB, 0x01, 0xFF, 0xE5,  /* frame=5 y=-21 x=-27 */
    IX_DRAW(0), 0x04, 0xEA, 0x01, 0x00, 0x17,  /* frame=4 y=-22 x=+23 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x88, 0x03,
    IX_DRAW(0), 0x0B, 0x2A, 0x00, 0xFF, 0xDD,  /* frame=11 y=+42 x=-35 */
    IX_DRAW(0), 0x0A, 0x15, 0x01, 0xFF, 0xE3,  /* frame=10 y=+21 x=-29 */
    IX_DRAW(0), 0x08, 0xEA, 0x01, 0xFF, 0xFB,  /* frame=8 y=-22 x=-5 */
    IX_DRAW(0), 0x07, 0xF7, 0x00, 0xFF, 0xD6,  /* frame=7 y=-9 x=-42 */
    IX_DRAW(0), 0x09, 0xF5, 0x01, 0x00, 0x2D,  /* frame=9 y=-11 x=+45 */
    IX_DRAW(0), 0x10, 0x08, 0x02, 0x00, 0x28,  /* frame=16 y=+8 x=+40 */
    IX_STEP_NEXT,  /* end of step 3 */
    0x88, 0x03,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(0), 0x06, 0x0D, 0x01, 0xFF, 0xDA,  /* frame=6 y=+13 x=-38 */
    IX_DRAW(0), 0x11, 0x07, 0x00, 0x00, 0x13,  /* frame=17 y=+7 x=+19 */
    IX_DRAW(0), 0x05, 0xEA, 0x01, 0xFF, 0xE0,  /* frame=5 y=-22 x=-32 */
    IX_DRAW(0), 0x04, 0xE9, 0x41, 0x00, 0x12,  /* frame=4 y=-23 x=+18 */
    IX_STEP_SCRIPT_END,  /* end of step 4 */
}; /* lab0890_script */
