/*
 * moon_anim_lab08b1.c — IMAGEXCEL animation script "lab08b1".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:16021
 * (LAB_08B1).  46 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08B1 — 46 bytes, 1 step(s) */
static const uint8_t lab08b1_script[] = {
    0xA8, 0x04,
    IX_DRAW(0), 0x16, 0x00, 0x00, 0x00, 0x00,  /* frame=22 y=+0 x=+0 */
    IX_DRAW(0), 0x11, 0xB6, 0x40, 0xFF, 0xEE,  /* frame=17 y=-74 x=-18 */
    IX_DRAW(0), 0x12, 0xCF, 0x00, 0xFF, 0xF2,  /* frame=18 y=-49 x=-14 */
    IX_DRAW(0), 0x13, 0xE4, 0x00, 0xFF, 0xEB,  /* frame=19 y=-28 x=-21 */
    IX_DRAW(0), 0x1A, 0xCF, 0x01, 0x00, 0x0B,  /* frame=26 y=-49 x=+11 */
    IX_DRAW(0), 0x1B, 0xE4, 0x01, 0xFF, 0xFA,  /* frame=27 y=-28 x=-6 */
    IX_DRAW(0), 0x1C, 0xF6, 0x00, 0x00, 0x1A,  /* frame=28 y=-10 x=+26 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab08b1_script */
