/*
 * moon_anim_lab087c.c — IMAGEXCEL animation script "lab087c".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15371
 * (LAB_087C).  56 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_087C — 56 bytes, 1 step(s) */
static const uint8_t lab087c_script[] = {
    IX_DRAW(1), 0x02, 0x0B, 0x01, 0xFF, 0x82,  /* frame=2 y=+11 x=-126 */
    IX_DRAW(1), 0x02, 0x00, 0x01, 0xFF, 0x9C,  /* frame=2 y=+0 x=-100 */
    IX_DRAW(1), 0x03, 0xF6, 0x00, 0xFF, 0xBA,  /* frame=3 y=-10 x=-70 */
    IX_DRAW(1), 0x03, 0xF6, 0x00, 0xFF, 0xD7,  /* frame=3 y=-10 x=-41 */
    IX_DRAW(1), 0x04, 0xFB, 0x00, 0xFF, 0xED,  /* frame=4 y=-5 x=-19 */
    IX_DRAW(0), 0x07, 0x0F, 0x01, 0xFF, 0xD1,  /* frame=7 y=+15 x=-47 */
    IX_DRAW(0), 0x08, 0x31, 0x00, 0xFF, 0xEE,  /* frame=8 y=+49 x=-18 */
    IX_DRAW(1), 0x10, 0x1D, 0x01, 0x00, 0x1A,  /* frame=16 y=+29 x=+26 */
    IX_DRAW(1), 0x0E, 0x16, 0x00, 0x00, 0x1A,  /* frame=14 y=+22 x=+26 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab087c_script */
