/*
 * moon_anim_lab00e1.c — IMAGEXCEL animation script "lab00e1".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2320
 * (LAB_00E1).  332 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00E1 — 332 bytes, 2 step(s) */
static const uint8_t lab00e1_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x0C, 0x2B, 0x00, 0xFF, 0xC6,  /* frame=12 y=+43 x=-58 */
    IX_DRAW(4), 0x26, 0x29, 0x00, 0xFF, 0xD0,  /* frame=38 y=+41 x=-48 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x88, 0x02,
    IX_DRAW(4), 0x0C, 0x2B, 0x00, 0xFF, 0xC6,  /* frame=12 y=+43 x=-58 */
    IX_DRAW(4), 0x25, 0x28, 0x00, 0xFF, 0xCD,  /* frame=37 y=+40 x=-51 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab00e1_script */
