/*
 * moon_anim_lab00dc.c — IMAGEXCEL animation script "lab00dc".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2246
 * (LAB_00DC).  38 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00DC — 38 bytes, 2 step(s) */
static const uint8_t lab00dc_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x13, 0xB6, 0x10, 0xFF, 0xD6,  /* frame=19 y=-74 x=-42 */
    IX_DRAW(4), 0x2A, 0xC0, 0x10, 0xFF, 0xDC,  /* frame=42 y=-64 x=-36 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(4), 0x13, 0xB6, 0x00, 0xFF, 0xD6,  /* frame=19 y=-74 x=-42 */
    IX_DRAW(4), 0x2A, 0xC0, 0x00, 0xFF, 0xDC,  /* frame=42 y=-64 x=-36 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab00dc_script */
