/*
 * moon_anim_lab0805.c — IMAGEXCEL animation script "lab0805".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14353
 * (LAB_0805).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0805 — 20 bytes, 1 step(s) */
static const uint8_t lab0805_script[] = {
    IX_DRAW(0), 0x1B, 0x00, 0x01, 0xFF, 0xEF,  /* frame=27 y=+0 x=-17 */
    IX_DRAW(0), 0x1C, 0x21, 0x01, 0xFF, 0xE2,  /* frame=28 y=+33 x=-30 */
    IX_DRAW(1), 0x42, 0xFD, 0x00, 0x00, 0x01,  /* frame=66 y=-3 x=+1 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0805_script */
