/*
 * moon_anim_lab082f.c — IMAGEXCEL animation script "lab082f".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14703
 * (LAB_082F).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_082F — 14 bytes, 1 step(s) */
static const uint8_t lab082f_script[] = {
    IX_DRAW(1), 0x4F, 0xEF, 0x00, 0x00, 0x03,  /* frame=79 y=-17 x=+3 */
    IX_DRAW(0), 0x1E, 0xFC, 0x01, 0xFF, 0xF3,  /* frame=30 y=-4 x=-13 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab082f_script */
