/*
 * moon_anim_lab0888.c — IMAGEXCEL animation script "lab0888".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15504
 * (LAB_0888).  46 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0888 — 46 bytes, 1 step(s) */
static const uint8_t lab0888_script[] = {
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0xC8, 0x01,  /* frame=0 y=+0 x=-14335 */
    IX_DRAW(0), 0x0D, 0x00, 0x00, 0x00, 0x00,  /* frame=13 y=+0 x=+0 */
    IX_DRAW(0), 0x03, 0x2B, 0x00, 0xFF, 0xD8,  /* frame=3 y=+43 x=-40 */
    IX_DRAW(0), 0x02, 0x0D, 0x01, 0xFF, 0xD8,  /* frame=2 y=+13 x=-40 */
    IX_DRAW(0), 0x01, 0xEB, 0x01, 0xFF, 0xDD,  /* frame=1 y=-21 x=-35 */
    IX_DRAW(0), 0x00, 0xF1, 0x41, 0x00, 0x05,  /* frame=0 y=-15 x=+5 */
    IX_DRAW(0), 0x0E, 0x0C, 0x40, 0xFF, 0xFE,  /* frame=14 y=+12 x=-2 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0888_script */
