/*
 * moon_anim_lab088f.c — IMAGEXCEL animation script "lab088f".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15540
 * (LAB_088F).  28 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_088F — 28 bytes, 1 step(s) */
static const uint8_t lab088f_script[] = {
    0x88, 0x03,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(0), 0x24, 0x2A, 0x00, 0xFF, 0xE0,  /* frame=36 y=+42 x=-32 */
    IX_DRAW(0), 0x23, 0x12, 0x01, 0xFF, 0xE7,  /* frame=35 y=+18 x=-25 */
    IX_DRAW(0), 0x22, 0xEC, 0x01, 0xFF, 0xE4,  /* frame=34 y=-20 x=-28 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab088f_script */
