/*
 * moon_anim_lab07df.c — IMAGEXCEL animation script "lab07df".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13985
 * (LAB_07DF).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07DF — 20 bytes, 1 step(s) */
static const uint8_t lab07df_script[] = {
    IX_DRAW(0), 0x07, 0x18, 0x01, 0xFF, 0xF3,  /* frame=7 y=+24 x=-13 */
    IX_DRAW(0), 0x06, 0xF8, 0x01, 0xFF, 0xF7,  /* frame=6 y=-8 x=-9 */
    IX_DRAW(3), 0x01, 0xFA, 0x00, 0x00, 0x01,  /* frame=1 y=-6 x=+1 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07df_script */
