/*
 * moon_anim_lab00d6.c — IMAGEXCEL animation script "lab00d6".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2105
 * (LAB_00D6).  124 bytes, 7 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00D6 — 124 bytes, 7 step(s) */
static const uint8_t lab00d6_script[] = {
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x01, 0xEF, 0x00, 0x00, 0x37,  /* frame=1 y=-17 x=+55 */
    IX_STEP_NEXT,  /* end of step 1 */
    0xB4, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x88, 0x02,
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x01, 0xF0, 0x00, 0x00, 0x37,  /* frame=1 y=-16 x=+55 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x88, 0x02,
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x02, 0xEF, 0x00, 0x00, 0x38,  /* frame=2 y=-17 x=+56 */
    IX_STEP_NEXT,  /* end of step 3 */
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x03, 0xEF, 0x00, 0x00, 0x34,  /* frame=3 y=-17 x=+52 */
    IX_DRAW(2), 0x04, 0x02, 0x00, 0x00, 0x28,  /* frame=4 y=+2 x=+40 */
    IX_STEP_NEXT,  /* end of step 4 */
    0x88, 0x04,
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x06, 0xEF, 0x00, 0x00, 0x31,  /* frame=6 y=-17 x=+49 */
    IX_DRAW(2), 0x05, 0x00, 0x00, 0x00, 0x1E,  /* frame=5 y=+0 x=+30 */
    IX_STEP_NEXT,  /* end of step 5 */
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x02, 0xEF, 0x00, 0x00, 0x38,  /* frame=2 y=-17 x=+56 */
    IX_STEP_NEXT,  /* end of step 6 */
    0x88, 0x14,
    IX_DRAW(2), 0x00, 0x9C, 0x00, 0x00, 0x44,  /* frame=0 y=-100 x=+68 */
    IX_DRAW(2), 0x01, 0xEF, 0x00, 0x00, 0x37,  /* frame=1 y=-17 x=+55 */
    IX_STEP_SCRIPT_END,  /* end of step 7 */
}; /* lab00d6_script */
