/*
 * moon_anim_lab07e1.c — IMAGEXCEL animation script "lab07e1".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13991
 * (LAB_07E1).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E1 — 14 bytes, 1 step(s) */
static const uint8_t lab07e1_script[] = {
    IX_DRAW(3), 0x00, 0xED, 0x00, 0x00, 0x02,  /* frame=0 y=-19 x=+2 */
    IX_DRAW(0), 0x0A, 0xF8, 0x01, 0xFF, 0xF6,  /* frame=10 y=-8 x=-10 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e1_script */
