/*
 * moon_anim_lab088b.c — IMAGEXCEL animation script "lab088b".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15523
 * (LAB_088B).  32 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_088B — 32 bytes, 1 step(s) */
static const uint8_t lab088b_script[] = {
    IX_DRAW(0), 0x19, 0x13, 0x01, 0xFF, 0xF1,  /* frame=25 y=+19 x=-15 */
    IX_DRAW(0), 0x18, 0x06, 0x03, 0xFF, 0xEE,  /* frame=24 y=+6 x=-18 */
    IX_DRAW(0), 0x17, 0xF5, 0x41, 0xFF, 0xE8,  /* frame=23 y=-11 x=-24 */
    IX_DRAW(0), 0x16, 0xD0, 0x41, 0xFF, 0xE9,  /* frame=22 y=-48 x=-23 */
    IX_DRAW(0), 0x15, 0xC6, 0x00, 0xFF, 0xF0,  /* frame=21 y=-58 x=-16 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab088b_script */
