/*
 * moon_anim_lab0825.c — IMAGEXCEL animation script "lab0825".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14651
 * (LAB_0825).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0825 — 20 bytes, 1 step(s) */
static const uint8_t lab0825_script[] = {
    IX_DRAW(0), 0x09, 0xFC, 0x01, 0xFF, 0xED,  /* frame=9 y=-4 x=-19 */
    IX_DRAW(1), 0x3E, 0xD9, 0x00, 0xFF, 0xF5,  /* frame=62 y=-39 x=-11 */
    IX_DRAW(1), 0x42, 0x13, 0x20, 0xFF, 0xF1,  /* frame=66 y=+19 x=-15 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0825_script */
