/*
 * moon_anim_lab07e0.c — IMAGEXCEL animation script "lab07e0".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13988
 * (LAB_07E0).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E0 — 20 bytes, 1 step(s) */
static const uint8_t lab07e0_script[] = {
    IX_DRAW(0), 0x09, 0x1B, 0x01, 0xFF, 0xF3,  /* frame=9 y=+27 x=-13 */
    IX_DRAW(0), 0x08, 0xF7, 0x01, 0xFF, 0xFC,  /* frame=8 y=-9 x=-4 */
    IX_DRAW(3), 0x01, 0xF7, 0x00, 0x00, 0x0C,  /* frame=1 y=-9 x=+12 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e0_script */
