/*
 * moon_anim_lab0877.c — IMAGEXCEL animation script "lab0877".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15343
 * (LAB_0877).  46 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0877 — 46 bytes, 1 step(s) */
static const uint8_t lab0877_script[] = {
    0x88, 0x02,
    IX_DRAW(1), 0x00, 0x0E, 0x00, 0xFF, 0x76,  /* frame=0 y=+14 x=-138 */
    IX_DRAW(1), 0x00, 0xF9, 0x01, 0xFF, 0x8C,  /* frame=0 y=-7 x=-116 */
    IX_DRAW(1), 0x00, 0xE5, 0x01, 0xFF, 0xA2,  /* frame=0 y=-27 x=-94 */
    IX_DRAW(1), 0x02, 0xD1, 0x00, 0xFF, 0xBE,  /* frame=2 y=-47 x=-66 */
    IX_DRAW(0), 0x15, 0xFD, 0x01, 0xFF, 0xF4,  /* frame=21 y=-3 x=-12 */
    IX_DRAW(0), 0x0F, 0xC8, 0x01, 0xFF, 0xF4,  /* frame=15 y=-56 x=-12 */
    IX_DRAW(0), 0x0E, 0xAF, 0x01, 0xFF, 0xC9,  /* frame=14 y=-81 x=-55 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0877_script */
