/*
 * moon_anim_lab0864.c — IMAGEXCEL animation script "lab0864".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15171
 * (LAB_0864).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0864 — 20 bytes, 1 step(s) */
static const uint8_t lab0864_script[] = {
    IX_DRAW(0), 0x37, 0x0F, 0x42, 0xFF, 0xFF,  /* frame=55 y=+15 x=-1 */
    IX_DRAW(0), 0x3F, 0xF2, 0x00, 0xFF, 0xE9,  /* frame=63 y=-14 x=-23 */
    IX_DRAW(0), 0x35, 0xF8, 0x00, 0x00, 0x11,  /* frame=53 y=-8 x=+17 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0864_script */
