/*
 * moon_anim_lab07e7.c — IMAGEXCEL animation script "lab07e7".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14009
 * (LAB_07E7).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E7 — 14 bytes, 1 step(s) */
static const uint8_t lab07e7_script[] = {
    IX_DRAW(0), 0x10, 0xF8, 0x01, 0xFF, 0xF3,  /* frame=16 y=-8 x=-13 */
    IX_DRAW(3), 0x00, 0xF1, 0x00, 0xFF, 0xFB,  /* frame=0 y=-15 x=-5 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e7_script */
