/*
 * moon_anim_anim_015e_2.c — IMAGEXCEL animation script "anim_015e_2".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14812
 * (LAB_083E).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_083E — 20 bytes, 1 step(s) */
static const uint8_t anim_015e_2_script[] = {
    IX_DRAW(0), 0x03, 0x19, 0x01, 0xFF, 0xCE,  /* frame=3 y=+25 x=-50 */
    IX_DRAW(0), 0x04, 0x0B, 0x03, 0xFF, 0xF2,  /* frame=4 y=+11 x=-14 */
    IX_DRAW(0), 0x12, 0x29, 0x00, 0xFF, 0xB9,  /* frame=18 y=+41 x=-71 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* anim_015e_2_script */
