/*
 * moon_anim_lab069f.c — IMAGEXCEL animation script "lab069f".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:12971
 * (LAB_069F).  60 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_069F — 60 bytes, 1 step(s) */
static const uint8_t lab069f_script[] = {
    IX_DRAW(0), 0x15, 0x00, 0x12, 0x00, 0x0B,  /* frame=21 y=+0 x=+11 */
    IX_DRAW(0), 0x16, 0x01, 0x1E, 0x00, 0x0B,  /* frame=22 y=+1 x=+11 */
    IX_DRAW(0), 0x17, 0x00, 0x00, 0x00, 0xBB,  /* frame=23 y=+0 x=+187 */
    IX_DRAW(0), 0x18, 0x01, 0x2F, 0x00, 0xC0,  /* frame=24 y=+1 x=+192 */
    IX_DRAW(0), 0x19, 0x00, 0x52, 0x00, 0x1C,  /* frame=25 y=+0 x=+28 */
    IX_DRAW(0), 0x1A, 0x01, 0x15, 0x00, 0x8F,  /* frame=26 y=+1 x=+143 */
    IX_DRAW(0), 0x1C, 0x00, 0x98, 0x00, 0x61,  /* frame=28 y=+0 x=+97 */
    IX_DRAW(0), 0x1B, 0x00, 0x58, 0x00, 0x9B,  /* frame=27 y=+0 x=+155 */
    IX_DRAW(0), 0x1E, 0x00, 0xD9, 0x00, 0x0B,  /* frame=30 y=+0 x=+11 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab069f_script */
