/*
 * moon_anim_lab08aa.c — IMAGEXCEL animation script "lab08aa".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15916
 * (LAB_08AA).  82 bytes, 3 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08AA — 82 bytes, 3 step(s) */
static const uint8_t lab08aa_script[] = {
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0x88, 0x01,  /* frame=0 y=+0 x=-30719 */
    IX_DRAW(0), 0x08, 0x2A, 0x00, 0xFF, 0xEB,  /* frame=8 y=+42 x=-21 */
    IX_DRAW(0), 0x07, 0x06, 0x01, 0xFF, 0xF8,  /* frame=7 y=+6 x=-8 */
    IX_DRAW(0), 0x06, 0xD5, 0x01, 0xFF, 0xE6,  /* frame=6 y=-43 x=-26 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(0), 0x0B, 0x1C, 0x01, 0xFF, 0xF3,  /* frame=11 y=+28 x=-13 */
    IX_DRAW(0), 0x0A, 0x01, 0x01, 0xFF, 0xFD,  /* frame=10 y=+1 x=-3 */
    IX_DRAW(0), 0x09, 0xDA, 0x01, 0x00, 0x03,  /* frame=9 y=-38 x=+3 */
    IX_DRAW(0), 0x01, 0x00, 0x02, 0x00, 0x21,  /* frame=1 y=+0 x=+33 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x88, 0x02,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(0), 0x0D, 0xD9, 0x01, 0xFF, 0xF8,  /* frame=13 y=-39 x=-8 */
    IX_DRAW(0), 0x0E, 0xF3, 0x01, 0x00, 0x25,  /* frame=14 y=-13 x=+37 */
    IX_DRAW(0), 0x0F, 0xFA, 0x02, 0x00, 0x41,  /* frame=15 y=-6 x=+65 */
    IX_STEP_SCRIPT_END,  /* end of step 3 */
}; /* lab08aa_script */
