/*
 * moon_anim_lab00ed.c — IMAGEXCEL animation script "lab00ed".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2529
 * (LAB_00ED).  240 bytes, 26 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00ED — 240 bytes, 26 step(s) */
static const uint8_t lab00ed_script[] = {
    IX_DRAW(4), 0x02, 0x5D, 0x00, 0xFF, 0xE3,  /* frame=2 y=+93 x=-29 */
    IX_DRAW(4), 0x23, 0xB0, 0x10, 0xFF, 0xE5,  /* frame=35 y=-80 x=-27 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(4), 0x01, 0x57, 0x00, 0xFF, 0xE4,  /* frame=1 y=+87 x=-28 */
    IX_DRAW(4), 0x23, 0xB0, 0x10, 0xFF, 0xE5,  /* frame=35 y=-80 x=-27 */
    IX_STEP_NEXT,  /* end of step 2 */
    IX_DRAW(4), 0x02, 0x55, 0x00, 0xFF, 0xE4,  /* frame=2 y=+85 x=-28 */
    IX_DRAW(4), 0x23, 0xB0, 0x00, 0xFF, 0xE5,  /* frame=35 y=-80 x=-27 */
    IX_STEP_NEXT,  /* end of step 3 */
    IX_DRAW(4), 0x00, 0x4E, 0x00, 0xFF, 0xE4,  /* frame=0 y=+78 x=-28 */
    IX_DRAW(4), 0x23, 0xB0, 0x00, 0xFF, 0xE5,  /* frame=35 y=-80 x=-27 */
    IX_STEP_NEXT,  /* end of step 4 */
    IX_DRAW(4), 0x02, 0x4A, 0x00, 0xFF, 0xE4,  /* frame=2 y=+74 x=-28 */
    IX_STEP_NEXT,  /* end of step 5 */
    IX_DRAW(4), 0x01, 0x42, 0x00, 0xFF, 0xE4,  /* frame=1 y=+66 x=-28 */
    IX_STEP_NEXT,  /* end of step 6 */
    IX_DRAW(4), 0x02, 0x3D, 0x00, 0xFF, 0xE4,  /* frame=2 y=+61 x=-28 */
    IX_DRAW(4), 0x23, 0xB0, 0x00, 0xFF, 0xE5,  /* frame=35 y=-80 x=-27 */
    IX_STEP_NEXT,  /* end of step 7 */
    IX_DRAW(4), 0x00, 0x35, 0x00, 0xFF, 0xE4,  /* frame=0 y=+53 x=-28 */
    IX_STEP_NEXT,  /* end of step 8 */
    IX_DRAW(4), 0x02, 0x30, 0x00, 0xFF, 0xE4,  /* frame=2 y=+48 x=-28 */
    IX_STEP_NEXT,  /* end of step 9 */
    IX_DRAW(4), 0x01, 0x27, 0x00, 0xFF, 0xE4,  /* frame=1 y=+39 x=-28 */
    IX_STEP_NEXT,  /* end of step 10 */
    IX_DRAW(4), 0x02, 0x22, 0x00, 0xFF, 0xE4,  /* frame=2 y=+34 x=-28 */
    IX_STEP_NEXT,  /* end of step 11 */
    IX_DRAW(4), 0x00, 0x19, 0x00, 0xFF, 0xE4,  /* frame=0 y=+25 x=-28 */
    IX_STEP_NEXT,  /* end of step 12 */
    IX_DRAW(4), 0x02, 0x12, 0x00, 0xFF, 0xE4,  /* frame=2 y=+18 x=-28 */
    IX_STEP_NEXT,  /* end of step 13 */
    IX_DRAW(4), 0x01, 0x0A, 0x00, 0xFF, 0xE4,  /* frame=1 y=+10 x=-28 */
    IX_STEP_NEXT,  /* end of step 14 */
    IX_DRAW(4), 0x02, 0x04, 0x00, 0xFF, 0xE4,  /* frame=2 y=+4 x=-28 */
    IX_STEP_NEXT,  /* end of step 15 */
    IX_DRAW(4), 0x00, 0xFC, 0x00, 0xFF, 0xE4,  /* frame=0 y=-4 x=-28 */
    IX_STEP_NEXT,  /* end of step 16 */
    IX_DRAW(4), 0x02, 0xF7, 0x00, 0xFF, 0xE4,  /* frame=2 y=-9 x=-28 */
    IX_STEP_NEXT,  /* end of step 17 */
    IX_DRAW(4), 0x02, 0xF3, 0x00, 0xFF, 0xE3,  /* frame=2 y=-13 x=-29 */
    IX_STEP_NEXT,  /* end of step 18 */
    IX_DRAW(4), 0x03, 0xF2, 0x00, 0xFF, 0xE4,  /* frame=3 y=-14 x=-28 */
    IX_STEP_NEXT,  /* end of step 19 */
    IX_DRAW(4), 0x04, 0xF1, 0x00, 0xFF, 0xE5,  /* frame=4 y=-15 x=-27 */
    IX_STEP_NEXT,  /* end of step 20 */
    IX_DRAW(4), 0x05, 0xF0, 0x00, 0xFF, 0xE6,  /* frame=5 y=-16 x=-26 */
    IX_STEP_NEXT,  /* end of step 21 */
    IX_DRAW(4), 0x06, 0xEF, 0x00, 0xFF, 0xE8,  /* frame=6 y=-17 x=-24 */
    IX_STEP_NEXT,  /* end of step 22 */
    IX_DRAW(4), 0x07, 0xF1, 0x00, 0xFF, 0xE6,  /* frame=7 y=-15 x=-26 */
    IX_STEP_NEXT,  /* end of step 23 */
    IX_DRAW(4), 0x08, 0xF1, 0x00, 0xFF, 0xE5,  /* frame=8 y=-15 x=-27 */
    IX_STEP_NEXT,  /* end of step 24 */
    IX_DRAW(4), 0x09, 0xF2, 0x00, 0xFF, 0xE4,  /* frame=9 y=-14 x=-28 */
    IX_STEP_NEXT,  /* end of step 25 */
    0x88, 0x0F,
    IX_DRAW(4), 0x0A, 0xF4, 0x00, 0xFF, 0xE3,  /* frame=10 y=-12 x=-29 */
    IX_STEP_SCRIPT_END,  /* end of step 26 */
}; /* lab00ed_script */
