/*
 * moon_anim_lab07f1.c — IMAGEXCEL animation script "lab07f1".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14101
 * (LAB_07F1).  104 bytes, 4 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07F1 — 104 bytes, 4 step(s) */
static const uint8_t lab07f1_script[] = {
    IX_DRAW(0), 0x13, 0x2C, 0x01, 0xFF, 0xEB,  /* frame=19 y=+44 x=-21 */
    IX_DRAW(0), 0x12, 0xF9, 0x01, 0xFF, 0xF2,  /* frame=18 y=-7 x=-14 */
    IX_DRAW(3), 0x01, 0xF1, 0x02, 0x00, 0x0C,  /* frame=1 y=-15 x=+12 */
    IX_STEP_NEXT,  /* end of step 1 */
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0x88, 0x01,  /* frame=0 y=+0 x=-30719 */
    IX_DRAW(1), 0x03, 0x16, 0x01, 0xFF, 0xF1,  /* frame=3 y=+22 x=-15 */
    IX_DRAW(1), 0x04, 0xFE, 0x01, 0x00, 0x05,  /* frame=4 y=-2 x=+5 */
    IX_DRAW(1), 0x05, 0xF7, 0x01, 0x00, 0x14,  /* frame=5 y=-9 x=+20 */
    IX_DRAW(3), 0x01, 0xDD, 0x02, 0x00, 0x1D,  /* frame=1 y=-35 x=+29 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x88, 0x04,
    IX_DRAW(1), 0x03, 0x16, 0x01, 0xFF, 0xF1,  /* frame=3 y=+22 x=-15 */
    IX_DRAW(1), 0x04, 0xFE, 0x01, 0x00, 0x05,  /* frame=4 y=-2 x=+5 */
    IX_DRAW(1), 0x05, 0xF7, 0x01, 0x00, 0x14,  /* frame=5 y=-9 x=+20 */
    IX_DRAW(3), 0x01, 0xDD, 0x02, 0x00, 0x1D,  /* frame=1 y=-35 x=+29 */
    IX_STEP_NEXT,  /* end of step 3 */
    0x88, 0x01,
    IX_DRAW(0), 0x13, 0x2C, 0x01, 0xFF, 0xEB,  /* frame=19 y=+44 x=-21 */
    IX_DRAW(0), 0x12, 0xF9, 0x01, 0xFF, 0xF2,  /* frame=18 y=-7 x=-14 */
    IX_DRAW(3), 0x01, 0xF1, 0x02, 0x00, 0x0C,  /* frame=1 y=-15 x=+12 */
    IX_STEP_SCRIPT_END,  /* end of step 4 */
}; /* lab07f1_script */
