/*
 * moon_anim_lab0885.c — IMAGEXCEL animation script "lab0885".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15483
 * (LAB_0885).  8 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0885 — 8 bytes, 1 step(s) */
static const uint8_t lab0885_script[] = {
    IX_DRAW(1), 0x1B, 0x2C, 0x00, 0xFF, 0x9F,  /* frame=27 y=+44 x=-97 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0885_script */
