/*
 * moon_anim_lab07f3.c — IMAGEXCEL animation script "lab07f3".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14123
 * (LAB_07F3).  26 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07F3 — 26 bytes, 1 step(s) */
static const uint8_t lab07f3_script[] = {
    IX_DRAW(1), 0x08, 0x2D, 0x00, 0xFF, 0xE9,  /* frame=8 y=+45 x=-23 */
    IX_DRAW(1), 0x07, 0x14, 0x01, 0xFF, 0xEF,  /* frame=7 y=+20 x=-17 */
    IX_DRAW(1), 0x06, 0xFB, 0x01, 0xFF, 0xE0,  /* frame=6 y=-5 x=-32 */
    IX_DRAW(3), 0x00, 0xEA, 0x00, 0xFF, 0xE0,  /* frame=0 y=-22 x=-32 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07f3_script */
