/*
 * moon_anim_lab086c.c — IMAGEXCEL animation script "lab086c".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15238
 * (LAB_086C).  8 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_086C — 8 bytes, 1 step(s) */
static const uint8_t lab086c_script[] = {
    IX_DRAW(0), 0x04, 0x18, 0x01, 0xFF, 0xF4,  /* frame=4 y=+24 x=-12 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab086c_script */
