/*
 * moon_anim_lab0835.c — IMAGEXCEL animation script "lab0835".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14721
 * (LAB_0835).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0835 — 14 bytes, 1 step(s) */
static const uint8_t lab0835_script[] = {
    IX_DRAW(0), 0x24, 0x01, 0x01, 0xFF, 0xEE,  /* frame=36 y=+1 x=-18 */
    IX_DRAW(1), 0x4F, 0xFE, 0x00, 0xFF, 0xF2,  /* frame=79 y=-2 x=-14 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0835_script */
