/*
 * moon_anim_lab0881.c — IMAGEXCEL animation script "lab0881".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15413
 * (LAB_0881).  68 bytes, 3 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0881 — 68 bytes, 3 step(s) */
static const uint8_t lab0881_script[] = {
    0x88, 0x02,
    IX_DRAW(1), 0x08, 0x22, 0x01, 0xFF, 0xE3,  /* frame=8 y=+34 x=-29 */
    IX_DRAW(1), 0x07, 0xE6, 0x01, 0xFF, 0xE2,  /* frame=7 y=-26 x=-30 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(1), 0x09, 0xDE, 0x01, 0xFF, 0xE7,  /* frame=9 y=-34 x=-25 */
    IX_DRAW(1), 0x0A, 0xEF, 0x03, 0x00, 0x10,  /* frame=10 y=-17 x=+16 */
    IX_STEP_NEXT,  /* end of step 2 */
    0x88, 0x04,
    IX_DRAW(1), 0x0B, 0xDB, 0x01, 0xFF, 0xF2,  /* frame=11 y=-37 x=-14 */
    IX_DRAW(1), 0x0C, 0xE7, 0x03, 0x00, 0x21,  /* frame=12 y=-25 x=+33 */
    IX_STEP_SCRIPT_END,  /* end of step 3 */
}; /* lab0881_script */
