/*
 * moon_anim_lab081b.c — IMAGEXCEL animation script "lab081b".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14571
 * (LAB_081B).  86 bytes, 3 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_081B — 86 bytes, 3 step(s) */
static const uint8_t lab081b_script[] = {
    IX_DRAW(1), 0x39, 0x30, 0x40, 0xFF, 0xFC,  /* frame=57 y=+48 x=-4 */
    IX_DRAW(1), 0x36, 0x04, 0x01, 0x00, 0x00,  /* frame=54 y=+4 x=+0 */
    IX_DRAW(1), 0x37, 0x18, 0x00, 0x00, 0x2F,  /* frame=55 y=+24 x=+47 */
    IX_DRAW(1), 0x38, 0x17, 0x42, 0x00, 0x51,  /* frame=56 y=+23 x=+81 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x03,
    IX_DRAW(1), 0x41, 0x2B, 0x40, 0xFF, 0xFE,  /* frame=65 y=+43 x=-2 */
    IX_DRAW(1), 0x3D, 0x1E, 0x01, 0x00, 0x03,  /* frame=61 y=+30 x=+3 */
    IX_DRAW(1), 0x3A, 0x05, 0x01, 0x00, 0x13,  /* frame=58 y=+5 x=+19 */
    IX_DRAW(1), 0x3B, 0x1A, 0x00, 0x00, 0x4E,  /* frame=59 y=+26 x=+78 */
    IX_DRAW(1), 0x3C, 0x19, 0x42, 0x00, 0x65,  /* frame=60 y=+25 x=+101 */
    IX_STEP_NEXT,  /* end of step 2 */
    IX_DRAW(1), 0x39, 0x30, 0x40, 0xFF, 0xFC,  /* frame=57 y=+48 x=-4 */
    IX_DRAW(1), 0x36, 0x04, 0x01, 0x00, 0x00,  /* frame=54 y=+4 x=+0 */
    IX_DRAW(1), 0x37, 0x18, 0x00, 0x00, 0x2F,  /* frame=55 y=+24 x=+47 */
    IX_DRAW(1), 0x38, 0x17, 0x42, 0x00, 0x51,  /* frame=56 y=+23 x=+81 */
    IX_STEP_SCRIPT_END,  /* end of step 3 */
}; /* lab081b_script */
