/*
 * moon_anim_lab087d.c — IMAGEXCEL animation script "lab087d".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15376
 * (LAB_087D).  50 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_087D — 50 bytes, 1 step(s) */
static const uint8_t lab087d_script[] = {
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0xF2,  /* frame=3 y=+9 x=-14 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0xD4,  /* frame=3 y=+9 x=-44 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0xB6,  /* frame=3 y=+9 x=-74 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0x97,  /* frame=3 y=+9 x=-105 */
    IX_DRAW(0), 0x07, 0x14, 0x01, 0xFF, 0xD6,  /* frame=7 y=+20 x=-42 */
    IX_DRAW(0), 0x08, 0x36, 0x00, 0xFF, 0xF3,  /* frame=8 y=+54 x=-13 */
    IX_DRAW(1), 0x10, 0x22, 0x01, 0x00, 0x20,  /* frame=16 y=+34 x=+32 */
    IX_DRAW(1), 0x0E, 0x1B, 0x00, 0x00, 0x20,  /* frame=14 y=+27 x=+32 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab087d_script */
