/*
 * moon_anim_anim_08fc.c — IMAGEXCEL animation script "anim_08fc".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:16567
 * (LAB_08FD).  8 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08FD — 8 bytes, 1 step(s) */
static const uint8_t anim_08fc_script[] = {
    IX_DRAW(0), 0x22, 0xFB, 0x00, 0xFF, 0xEF,  /* frame=34 y=-5 x=-17 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* anim_08fc_script */
