/*
 * moon_anim_lab07eb.c — IMAGEXCEL animation script "lab07eb".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14040
 * (LAB_07EB).  24 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07EB — 24 bytes, 1 step(s) */
static const uint8_t lab07eb_script[] = {
    0xA4, 0x0B, 0xA0, 0x01,
    IX_DRAW(0), 0x05, 0x00, 0x00, 0x00, 0x00,  /* frame=5 y=+0 x=+0 */
    IX_DRAW(3), 0x0A, 0x08, 0x02, 0x00, 0x42,  /* frame=10 y=+8 x=+66 */
    IX_DRAW(3), 0x0D, 0x08, 0x00, 0x00, 0x0C,  /* frame=13 y=+8 x=+12 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07eb_script */
