/*
 * moon_anim_lab0815.c — IMAGEXCEL animation script "lab0815".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14476
 * (LAB_0815).  120 bytes, 4 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0815 — 120 bytes, 4 step(s) */
static const uint8_t lab0815_script[] = {
    0xD0, 0x00, 0xB0, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xB4, 0x01, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(1), 0x3E, 0xD2, 0x00, 0x00, 0x1C,  /* frame=62 y=-46 x=+28 */
    IX_DRAW(1), 0x0B, 0xFF, 0x00, 0x00, 0x00,  /* frame=11 y=-1 x=+0 */
    IX_DRAW(1), 0x0C, 0x16, 0x80, 0xFF, 0xF7,  /* frame=12 y=+22 x=-9 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(1), 0x3E, 0xD2, 0x00, 0x00, 0x1C,  /* frame=62 y=-46 x=+28 */
    IX_DRAW(1), 0x0D, 0x1A, 0x80, 0xFF, 0xE4,  /* frame=13 y=+26 x=-28 */
    IX_DRAW(1), 0x0B, 0xFF, 0x00, 0x00, 0x00,  /* frame=11 y=-1 x=+0 */
    IX_DRAW(1), 0x05, 0x1E, 0x80, 0x00, 0x28,  /* frame=5 y=+30 x=+40 */
    IX_DRAW(1), 0x0E, 0x18, 0x80, 0x00, 0x08,  /* frame=14 y=+24 x=+8 */
    IX_STEP_NEXT,  /* end of step 2 */
    IX_DRAW(1), 0x3E, 0xD2, 0x00, 0x00, 0x1C,  /* frame=62 y=-46 x=+28 */
    IX_DRAW(1), 0x0B, 0xFF, 0x00, 0x00, 0x00,  /* frame=11 y=-1 x=+0 */
    IX_DRAW(1), 0x08, 0x2C, 0x80, 0x00, 0x34,  /* frame=8 y=+44 x=+52 */
    IX_DRAW(1), 0x0F, 0x18, 0x80, 0x00, 0x08,  /* frame=15 y=+24 x=+8 */
    IX_STEP_NEXT,  /* end of step 3 */
    0x88, 0x02,
    IX_DRAW(1), 0x3E, 0xD2, 0x00, 0x00, 0x1C,  /* frame=62 y=-46 x=+28 */
    IX_DRAW(1), 0x0A, 0x34, 0x90, 0x00, 0x33,  /* frame=10 y=+52 x=+51 */
    IX_DRAW(1), 0x0B, 0xFF, 0x00, 0x00, 0x00,  /* frame=11 y=-1 x=+0 */
    IX_DRAW(1), 0x07, 0x19, 0x80, 0x00, 0x0A,  /* frame=7 y=+25 x=+10 */
    IX_STEP_SCRIPT_END,  /* end of step 4 */
}; /* lab0815_script */
