/*
 * moon_anim_lab0843.c — IMAGEXCEL animation script "lab0843".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14824
 * (LAB_0843).  16 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0843 — 16 bytes, 1 step(s) */
static const uint8_t lab0843_script[] = {
    0x88, 0x03,
    IX_DRAW(0), 0x1D, 0x0C, 0x01, 0xFF, 0xDF,  /* frame=29 y=+12 x=-33 */
    IX_DRAW(0), 0x21, 0x1B, 0x00, 0x00, 0x1A,  /* frame=33 y=+27 x=+26 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0843_script */
