/*
 * moon_anim_lab0828.c — IMAGEXCEL animation script "lab0828".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14660
 * (LAB_0828).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0828 — 20 bytes, 1 step(s) */
static const uint8_t lab0828_script[] = {
    IX_DRAW(0), 0x00, 0x04, 0x01, 0xFF, 0xE6,  /* frame=0 y=+4 x=-26 */
    IX_DRAW(0), 0x01, 0x1E, 0x01, 0x00, 0x0B,  /* frame=1 y=+30 x=+11 */
    IX_DRAW(1), 0x45, 0xF4, 0x00, 0xFF, 0xEF,  /* frame=69 y=-12 x=-17 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0828_script */
