/*
 * moon_anim_lab087f.c — IMAGEXCEL animation script "lab087f".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15403
 * (LAB_087F).  54 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_087F — 54 bytes, 1 step(s) */
static const uint8_t lab087f_script[] = {
    0xA4, 0x1C, 0x88, 0x02,
    0xB4, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(1), 0x00, 0xF3, 0x00, 0xFF, 0xCD,  /* frame=0 y=-13 x=-51 */
    IX_DRAW(1), 0x01, 0x00, 0x00, 0xFF, 0xBC,  /* frame=1 y=+0 x=-68 */
    IX_DRAW(1), 0x02, 0x0A, 0x00, 0xFF, 0xA7,  /* frame=2 y=+10 x=-89 */
    IX_DRAW(1), 0x03, 0x09, 0x00, 0xFF, 0x91,  /* frame=3 y=+9 x=-111 */
    IX_DRAW(0), 0x0C, 0xE3, 0x00, 0xFF, 0xC0,  /* frame=12 y=-29 x=-64 */
    IX_DRAW(0), 0x0D, 0xC2, 0x00, 0x00, 0x00,  /* frame=13 y=-62 x=+0 */
    IX_DRAW(0), 0x13, 0xEB, 0x00, 0xFF, 0xA2,  /* frame=19 y=-21 x=-94 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab087f_script */
