/*
 * moon_anim_lab082c.c — IMAGEXCEL animation script "lab082c".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14694
 * (LAB_082C).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_082C — 14 bytes, 1 step(s) */
static const uint8_t lab082c_script[] = {
    IX_DRAW(0), 0x1A, 0x00, 0x01, 0xFF, 0xEE,  /* frame=26 y=+0 x=-18 */
    IX_DRAW(1), 0x4A, 0xFC, 0x00, 0x00, 0x02,  /* frame=74 y=-4 x=+2 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab082c_script */
