/*
 * moon_anim_lab00e4.c — IMAGEXCEL animation script "lab00e4".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2368
 * (LAB_00E4).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00E4 — 14 bytes, 1 step(s) */
static const uint8_t lab00e4_script[] = {
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(4), 0x23, 0xF2, 0x00, 0xFF, 0xE4,  /* frame=35 y=-14 x=-28 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab00e4_script */
