/*
 * moon_anim_lab0834.c — IMAGEXCEL animation script "lab0834".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14718
 * (LAB_0834).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0834 — 14 bytes, 1 step(s) */
static const uint8_t lab0834_script[] = {
    IX_DRAW(0), 0x23, 0x01, 0x01, 0xFF, 0xED,  /* frame=35 y=+1 x=-19 */
    IX_DRAW(1), 0x4F, 0xFE, 0x00, 0xFF, 0xF3,  /* frame=79 y=-2 x=-13 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0834_script */
