/*
 * moon_anim_lab07dc.c — IMAGEXCEL animation script "lab07dc".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13975
 * (LAB_07DC).  44 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07DC — 44 bytes, 2 step(s) */
static const uint8_t lab07dc_script[] = {
    0xD0, 0x00, 0x00, 0x13, 0x2C, 0x01, 0xFF, 0xEB,
    IX_DRAW(0), 0x12, 0xF9, 0x01, 0xFF, 0xF2,  /* frame=18 y=-7 x=-14 */
    IX_DRAW(3), 0x01, 0xF1, 0x00, 0x00, 0x0C,  /* frame=1 y=-15 x=+12 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    IX_DRAW(0), 0x01, 0x2D, 0x00, 0xFF, 0xF3,  /* frame=1 y=+45 x=-13 */
    IX_DRAW(0), 0x00, 0xF7, 0x01, 0xFF, 0xF7,  /* frame=0 y=-9 x=-9 */
    IX_DRAW(3), 0x01, 0xFA, 0x00, 0x00, 0x04,  /* frame=1 y=-6 x=+4 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab07dc_script */
