/*
 * moon_anim_lab0f54.c — IMAGEXCEL animation script "lab0f54".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:27633
 * (LAB_0F54).  16 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0F54 — 16 bytes, 2 step(s) */
static const uint8_t lab0f54_script[] = {
    IX_DRAW(0), 0x06, 0x02, 0x00, 0xFF, 0xD7,  /* frame=6 y=+2 x=-41 */
    IX_STEP_NEXT,  /* end of step 1 */
    IX_DRAW(0), 0x07, 0x02, 0x00, 0xFF, 0xD7,  /* frame=7 y=+2 x=-41 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab0f54_script */
