/*
 * moon_anim_lab08a5.c — IMAGEXCEL animation script "lab08a5".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15901
 * (LAB_08A5).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_08A5 — 20 bytes, 1 step(s) */
static const uint8_t lab08a5_script[] = {
    IX_DRAW(0), 0x08, 0x2A, 0x00, 0xFF, 0xEB,  /* frame=8 y=+42 x=-21 */
    IX_DRAW(0), 0x07, 0x06, 0x01, 0xFF, 0xF8,  /* frame=7 y=+6 x=-8 */
    IX_DRAW(0), 0x06, 0xD5, 0x01, 0xFF, 0xE6,  /* frame=6 y=-43 x=-26 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab08a5_script */
