/*
 * moon_anim_lab089c.c — IMAGEXCEL animation script "lab089c".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15776
 * (LAB_089C).  34 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_089C — 34 bytes, 1 step(s) */
static const uint8_t lab089c_script[] = {
    0x88, 0x02,
    IX_DRAW(0), 0x1E, 0xF6, 0x01, 0xFF, 0xE4,  /* frame=30 y=-10 x=-28 */
    IX_DRAW(0), 0x1D, 0x33, 0x40, 0x00, 0x24,  /* frame=29 y=+51 x=+36 */
    IX_DRAW(0), 0x1C, 0x32, 0x40, 0xFF, 0xD5,  /* frame=28 y=+50 x=-43 */
    IX_DRAW(0), 0x21, 0x2D, 0x41, 0xFF, 0xE1,  /* frame=33 y=+45 x=-31 */
    IX_DRAW(0), 0x20, 0x37, 0x40, 0xFF, 0xDF,  /* frame=32 y=+55 x=-33 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab089c_script */
