/*
 * moon_anim_lab0873.c — IMAGEXCEL animation script "lab0873".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15321
 * (LAB_0873).  58 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0873 — 58 bytes, 1 step(s) */
static const uint8_t lab0873_script[] = {
    0xA8, 0x04,
    IX_DRAW(0), 0x16, 0x00, 0x00, 0x00, 0x00,  /* frame=22 y=+0 x=+0 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0xF2,  /* frame=3 y=+9 x=-14 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0xD4,  /* frame=3 y=+9 x=-44 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0xB6,  /* frame=3 y=+9 x=-74 */
    IX_DRAW(1), 0x03, 0x09, 0x01, 0xFF, 0x97,  /* frame=3 y=+9 x=-105 */
    IX_DRAW(0), 0x07, 0x14, 0x01, 0xFF, 0xD6,  /* frame=7 y=+20 x=-42 */
    IX_DRAW(0), 0x08, 0x36, 0x00, 0xFF, 0xF3,  /* frame=8 y=+54 x=-13 */
    IX_DRAW(1), 0x10, 0x22, 0x01, 0x00, 0x20,  /* frame=16 y=+34 x=+32 */
    IX_DRAW(1), 0x0E, 0x1B, 0x00, 0x00, 0x20,  /* frame=14 y=+27 x=+32 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0873_script */
