/*
 * moon_anim_anim_08fc_8.c — IMAGEXCEL animation script "anim_08fc_8".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:16581
 * (LAB_0904).  8 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0904 — 8 bytes, 1 step(s) */
static const uint8_t anim_08fc_8_script[] = {
    IX_DRAW(0), 0x29, 0xFC, 0x00, 0xFF, 0xEF,  /* frame=41 y=-4 x=-17 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* anim_08fc_8_script */
