/*
 * moon_anim_lab07dd.c — IMAGEXCEL animation script "lab07dd".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13979
 * (LAB_07DD).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07DD — 20 bytes, 1 step(s) */
static const uint8_t lab07dd_script[] = {
    IX_DRAW(0), 0x03, 0x2E, 0x00, 0xFF, 0xF3,  /* frame=3 y=+46 x=-13 */
    IX_DRAW(0), 0x02, 0xF7, 0x01, 0xFF, 0xF7,  /* frame=2 y=-9 x=-9 */
    IX_DRAW(3), 0x01, 0xFA, 0x00, 0x00, 0x03,  /* frame=1 y=-6 x=+3 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07dd_script */
