/*
 * moon_anim_lab0894.c — IMAGEXCEL animation script "lab0894".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15615
 * (LAB_0894).  112 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0894 — 112 bytes, 2 step(s) */
static const uint8_t lab0894_script[] = {
    0x94, 0x08,
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0x88, 0x01,  /* frame=0 y=+0 x=-30719 */
    IX_DRAW(0), 0x0B, 0x2A, 0x00, 0xFF, 0xDD,  /* frame=11 y=+42 x=-35 */
    IX_DRAW(0), 0x0A, 0x15, 0x00, 0xFF, 0xE3,  /* frame=10 y=+21 x=-29 */
    IX_DRAW(0), 0x08, 0xEA, 0x00, 0xFF, 0xFB,  /* frame=8 y=-22 x=-5 */
    IX_DRAW(0), 0x07, 0xF7, 0x00, 0xFF, 0xD6,  /* frame=7 y=-9 x=-42 */
    IX_DRAW(0), 0x09, 0xF5, 0x00, 0x00, 0x2D,  /* frame=9 y=-11 x=+45 */
    IX_DRAW(2), 0x0C, 0x0A, 0x00, 0x00, 0x28,  /* frame=12 y=+10 x=+40 */
    IX_DRAW(2), 0x12, 0xEE, 0x00, 0x00, 0x46,  /* frame=18 y=-18 x=+70 */
    IX_DRAW(2), 0x11, 0x15, 0x00, 0x00, 0x47,  /* frame=17 y=+21 x=+71 */
    IX_DRAW(2), 0x0F, 0xED, 0x00, 0x00, 0x49,  /* frame=15 y=-19 x=+73 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x01,
    IX_DRAW(0), 0x06, 0x0D, 0x00, 0xFF, 0xD9,  /* frame=6 y=+13 x=-39 */
    IX_DRAW(2), 0x19, 0x01, 0x00, 0x00, 0x11,  /* frame=25 y=+1 x=+17 */
    IX_DRAW(0), 0x05, 0xEA, 0x00, 0xFF, 0xE0,  /* frame=5 y=-22 x=-32 */
    IX_DRAW(2), 0x17, 0xF5, 0x00, 0x00, 0x32,  /* frame=23 y=-11 x=+50 */
    IX_DRAW(2), 0x18, 0xED, 0x00, 0x00, 0x39,  /* frame=24 y=-19 x=+57 */
    IX_DRAW(0), 0x04, 0xE9, 0x00, 0x00, 0x12,  /* frame=4 y=-23 x=+18 */
    IX_DRAW(2), 0x10, 0x04, 0x00, 0x00, 0x4A,  /* frame=16 y=+4 x=+74 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab0894_script */
