/*
 * moon_anim_lab07f4.c — IMAGEXCEL animation script "lab07f4".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14127
 * (LAB_07F4).  26 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07F4 — 26 bytes, 1 step(s) */
static const uint8_t lab07f4_script[] = {
    IX_DRAW(0), 0x16, 0x2D, 0x01, 0xFF, 0xED,  /* frame=22 y=+45 x=-19 */
    IX_DRAW(0), 0x15, 0x13, 0x01, 0xFF, 0xEF,  /* frame=21 y=+19 x=-17 */
    IX_DRAW(0), 0x14, 0xF8, 0x01, 0xFF, 0xFA,  /* frame=20 y=-8 x=-6 */
    IX_DRAW(3), 0x02, 0x09, 0x00, 0x00, 0x0E,  /* frame=2 y=+9 x=+14 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07f4_script */
