/*
 * moon_anim_anim_015e_3.c — IMAGEXCEL animation script "anim_015e_3".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14815
 * (LAB_083F).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_083F — 14 bytes, 1 step(s) */
static const uint8_t anim_015e_3_script[] = {
    IX_DRAW(0), 0x05, 0x07, 0x03, 0xFF, 0xDE,  /* frame=5 y=+7 x=-34 */
    IX_DRAW(0), 0x0E, 0x02, 0x00, 0xFF, 0xD4,  /* frame=14 y=+2 x=-44 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* anim_015e_3_script */
