/*
 * moon_anim_lab07de.c — IMAGEXCEL animation script "lab07de".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:13982
 * (LAB_07DE).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07DE — 20 bytes, 1 step(s) */
static const uint8_t lab07de_script[] = {
    IX_DRAW(0), 0x05, 0x23, 0x01, 0xFF, 0xF3,  /* frame=5 y=+35 x=-13 */
    IX_DRAW(0), 0x04, 0xF7, 0x01, 0xFF, 0xFD,  /* frame=4 y=-9 x=-3 */
    IX_DRAW(3), 0x01, 0xFA, 0x00, 0x00, 0x06,  /* frame=1 y=-6 x=+6 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07de_script */
