/*
 * moon_anim_lab0830.c — IMAGEXCEL animation script "lab0830".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14706
 * (LAB_0830).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0830 — 14 bytes, 1 step(s) */
static const uint8_t lab0830_script[] = {
    IX_DRAW(1), 0x4F, 0xEF, 0x00, 0x00, 0x00,  /* frame=79 y=-17 x=+0 */
    IX_DRAW(0), 0x1F, 0xFC, 0x01, 0xFF, 0xF3,  /* frame=31 y=-4 x=-13 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0830_script */
