/*
 * moon_anim_lab081e.c — IMAGEXCEL animation script "lab081e".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14629
 * (LAB_081E).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_081E — 20 bytes, 1 step(s) */
static const uint8_t lab081e_script[] = {
    IX_DRAW(0), 0x01, 0xFB, 0x01, 0xFF, 0xF0,  /* frame=1 y=-5 x=-16 */
    IX_DRAW(1), 0x3E, 0xDE, 0x00, 0x00, 0x09,  /* frame=62 y=-34 x=+9 */
    IX_DRAW(1), 0x42, 0x11, 0x20, 0x00, 0x06,  /* frame=66 y=+17 x=+6 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab081e_script */
