/*
 * moon_anim_lab00dd.c — IMAGEXCEL animation script "lab00dd".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2252
 * (LAB_00DD).  44 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00DD — 44 bytes, 2 step(s) */
static const uint8_t lab00dd_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x11, 0xC5, 0x00, 0xFF, 0xB8,  /* frame=17 y=-59 x=-72 */
    IX_DRAW(4), 0x2F, 0xD0, 0x00, 0xFF, 0xC1,  /* frame=47 y=-48 x=-63 */
    IX_DRAW(4), 0x2F, 0xD1, 0x00, 0xFF, 0xC1,  /* frame=47 y=-47 x=-63 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(4), 0x11, 0xC5, 0x00, 0xFF, 0xB8,  /* frame=17 y=-59 x=-72 */
    IX_DRAW(4), 0x2F, 0xD0, 0x00, 0xFF, 0xC1,  /* frame=47 y=-48 x=-63 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab00dd_script */
