/*
 * moon_anim_registry.h — registry of all IMAGEXCEL animation scripts.
 *
 * Auto-generated by tools/extract_scripts.py (or a companion script).
 * Each AnimEntry maps a script name to its byte array, CEL file slots,
 * and initial entity parameters.
 *
 * CEL slots without a known mapping have cel_files[slot] = NULL;
 * moon-anim-viewer renders a placeholder box for those slots.
 *
 * To add a mapping: edit the appropriate entry's cel_files[] below,
 * or extend KNOWN_CELS in tools/extract_scripts.py to auto-generate.
 */

#ifndef MOON_ANIM_REGISTRY_H
#define MOON_ANIM_REGISTRY_H

#include <stdint.h>
#include "imagexcel.h"

/* ------------------------------------------------------------------ */
/* Include all auto-generated animation script arrays                  */
/* ------------------------------------------------------------------ */

#include "moon_anim_anim_003a.c"
#include "moon_anim_anim_015e.c"
#include "moon_anim_anim_015e_2.c"
#include "moon_anim_anim_015e_3.c"
#include "moon_anim_anim_08fc.c"
#include "moon_anim_anim_08fc_2.c"
#include "moon_anim_anim_08fc_3.c"
#include "moon_anim_anim_08fc_4.c"
#include "moon_anim_anim_08fc_5.c"
#include "moon_anim_anim_08fc_6.c"
#include "moon_anim_anim_08fc_7.c"
#include "moon_anim_anim_08fc_8.c"
#include "moon_anim_dw1_walk.c"
#include "moon_anim_kn_walk.c"
#include "moon_anim_lab00d2.c"
#include "moon_anim_lab00d3.c"
#include "moon_anim_lab00d4.c"
#include "moon_anim_lab00d5.c"
#include "moon_anim_lab00d6.c"
#include "moon_anim_lab00db.c"
#include "moon_anim_lab00dc.c"
#include "moon_anim_lab00dd.c"
#include "moon_anim_lab00df.c"
#include "moon_anim_lab00e1.c"
#include "moon_anim_lab00e2.c"
#include "moon_anim_lab00e3.c"
#include "moon_anim_lab00e4.c"
#include "moon_anim_lab00e5.c"
#include "moon_anim_lab00e6.c"
#include "moon_anim_lab00e8.c"
#include "moon_anim_lab00e9.c"
#include "moon_anim_lab00eb.c"
#include "moon_anim_lab00ec.c"
#include "moon_anim_lab00ed.c"
#include "moon_anim_lab00ee.c"
#include "moon_anim_lab069f.c"
#include "moon_anim_lab07db.c"
#include "moon_anim_lab07dc.c"
#include "moon_anim_lab07dd.c"
#include "moon_anim_lab07de.c"
#include "moon_anim_lab07df.c"
#include "moon_anim_lab07e0.c"
#include "moon_anim_lab07e1.c"
#include "moon_anim_lab07e2.c"
#include "moon_anim_lab07e3.c"
#include "moon_anim_lab07e4.c"
#include "moon_anim_lab07e5.c"
#include "moon_anim_lab07e6.c"
#include "moon_anim_lab07e7.c"
#include "moon_anim_lab07e8.c"
#include "moon_anim_lab07eb.c"
#include "moon_anim_lab07ed.c"
#include "moon_anim_lab07f1.c"
#include "moon_anim_lab07f3.c"
#include "moon_anim_lab07f4.c"
#include "moon_anim_lab07fc.c"
#include "moon_anim_lab07ff.c"
#include "moon_anim_lab0800.c"
#include "moon_anim_lab0803.c"
#include "moon_anim_lab0804.c"
#include "moon_anim_lab0805.c"
#include "moon_anim_lab0806.c"
#include "moon_anim_lab0807.c"
#include "moon_anim_lab0808.c"
#include "moon_anim_lab0809.c"
#include "moon_anim_lab080a.c"
#include "moon_anim_lab080b.c"
#include "moon_anim_lab080c.c"
#include "moon_anim_lab080d.c"
#include "moon_anim_lab0814.c"
#include "moon_anim_lab0815.c"
#include "moon_anim_lab0816.c"
#include "moon_anim_lab081a.c"
#include "moon_anim_lab081b.c"
#include "moon_anim_lab081c.c"
#include "moon_anim_lab081d.c"
#include "moon_anim_lab081e.c"
#include "moon_anim_lab081f.c"
#include "moon_anim_lab0820.c"
#include "moon_anim_lab0821.c"
#include "moon_anim_lab0822.c"
#include "moon_anim_lab0823.c"
#include "moon_anim_lab0824.c"
#include "moon_anim_lab0825.c"
#include "moon_anim_lab0826.c"
#include "moon_anim_lab0827.c"
#include "moon_anim_lab0828.c"
#include "moon_anim_lab082b.c"
#include "moon_anim_lab082c.c"
#include "moon_anim_lab082d.c"
#include "moon_anim_lab082e.c"
#include "moon_anim_lab082f.c"
#include "moon_anim_lab0830.c"
#include "moon_anim_lab0831.c"
#include "moon_anim_lab0832.c"
#include "moon_anim_lab0833.c"
#include "moon_anim_lab0834.c"
#include "moon_anim_lab0835.c"
#include "moon_anim_lab0843.c"
#include "moon_anim_lab0849.c"
#include "moon_anim_lab0853.c"
#include "moon_anim_lab0854.c"
#include "moon_anim_lab0855.c"
#include "moon_anim_lab085b.c"
#include "moon_anim_lab085c.c"
#include "moon_anim_lab0863.c"
#include "moon_anim_lab0864.c"
#include "moon_anim_lab0866.c"
#include "moon_anim_lab086c.c"
#include "moon_anim_lab086d.c"
#include "moon_anim_lab086e.c"
#include "moon_anim_lab086f.c"
#include "moon_anim_lab0870.c"
#include "moon_anim_lab0873.c"
#include "moon_anim_lab0874.c"
#include "moon_anim_lab0875.c"
#include "moon_anim_lab0876.c"
#include "moon_anim_lab0877.c"
#include "moon_anim_lab0879.c"
#include "moon_anim_lab087a.c"
#include "moon_anim_lab087b.c"
#include "moon_anim_lab087c.c"
#include "moon_anim_lab087d.c"
#include "moon_anim_lab087f.c"
#include "moon_anim_lab0880.c"
#include "moon_anim_lab0881.c"
#include "moon_anim_lab0883.c"
#include "moon_anim_lab0885.c"
#include "moon_anim_lab0887.c"
#include "moon_anim_lab0888.c"
#include "moon_anim_lab088b.c"
#include "moon_anim_lab088f.c"
#include "moon_anim_lab0890.c"
#include "moon_anim_lab0893.c"
#include "moon_anim_lab0894.c"
#include "moon_anim_lab0895.c"
#include "moon_anim_lab0896.c"
#include "moon_anim_lab0898.c"
#include "moon_anim_lab089b.c"
#include "moon_anim_lab089c.c"
#include "moon_anim_lab089d.c"
#include "moon_anim_lab089e.c"
#include "moon_anim_lab08a0.c"
#include "moon_anim_lab08a3.c"
#include "moon_anim_lab08a5.c"
#include "moon_anim_lab08a6.c"
#include "moon_anim_lab08a7.c"
#include "moon_anim_lab08a8.c"
#include "moon_anim_lab08a9.c"
#include "moon_anim_lab08aa.c"
#include "moon_anim_lab08b0.c"
#include "moon_anim_lab08b1.c"
#include "moon_anim_lab08b2.c"
#include "moon_anim_lab08b3.c"
#include "moon_anim_lab08b6.c"
#include "moon_anim_lab08bc.c"
#include "moon_anim_lab08be.c"
#include "moon_anim_lab0978.c"
#include "moon_anim_lab0979.c"
#include "moon_anim_lab097a.c"
#include "moon_anim_lab0f54.c"
#include "moon_anim_lab0f57.c"

/* ------------------------------------------------------------------ */
/* AnimEntry — one entry per animation script                          */
/* ------------------------------------------------------------------ */

typedef struct {
    const char    *name;               /* human-readable script name   */
    const uint8_t *script;             /* script byte array            */
    const char    *cel_files[IX_SLOTS]; /* NULL = slot not yet mapped  */
    int16_t        base_x;
    int16_t        base_y;
    int16_t        vel_y;
    uint8_t        direction;
} AnimEntry;

/* ------------------------------------------------------------------ */
/* Registry table — 162 auto-generated scripts                         */
/* ------------------------------------------------------------------ */

static const AnimEntry g_anim_registry[] = {
    { "anim_003a", anim_003a_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_015e", anim_015e_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_015e_2", anim_015e_2_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_015e_3", anim_015e_3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc", anim_08fc_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_2", anim_08fc_2_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_3", anim_08fc_3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_4", anim_08fc_4_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_5", anim_08fc_5_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_6", anim_08fc_6_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_7", anim_08fc_7_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "anim_08fc_8", anim_08fc_8_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "dw1_walk", dw1_walk_script, { NULL, NULL, NULL, "dw1.cel", NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "kn_walk", kn_walk_script, { NULL, NULL, NULL, "dw1.cel", NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00d2", lab00d2_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00d3", lab00d3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00d4", lab00d4_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00d5", lab00d5_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00d6", lab00d6_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00db", lab00db_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00dc", lab00dc_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00dd", lab00dd_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00df", lab00df_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e1", lab00e1_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e2", lab00e2_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e3", lab00e3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e4", lab00e4_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e5", lab00e5_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e6", lab00e6_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e8", lab00e8_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00e9", lab00e9_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00eb", lab00eb_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00ec", lab00ec_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00ed", lab00ed_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab00ee", lab00ee_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab069f", lab069f_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07db", lab07db_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07dc", lab07dc_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07dd", lab07dd_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07de", lab07de_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07df", lab07df_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e0", lab07e0_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e1", lab07e1_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e2", lab07e2_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e3", lab07e3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e4", lab07e4_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e5", lab07e5_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e6", lab07e6_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e7", lab07e7_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07e8", lab07e8_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07eb", lab07eb_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07ed", lab07ed_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07f1", lab07f1_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07f3", lab07f3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07f4", lab07f4_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07fc", lab07fc_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab07ff", lab07ff_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0800", lab0800_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0803", lab0803_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0804", lab0804_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0805", lab0805_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0806", lab0806_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0807", lab0807_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0808", lab0808_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0809", lab0809_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab080a", lab080a_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab080b", lab080b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab080c", lab080c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab080d", lab080d_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0814", lab0814_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0815", lab0815_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0816", lab0816_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab081a", lab081a_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab081b", lab081b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab081c", lab081c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab081d", lab081d_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab081e", lab081e_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab081f", lab081f_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0820", lab0820_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0821", lab0821_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0822", lab0822_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0823", lab0823_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0824", lab0824_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0825", lab0825_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0826", lab0826_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0827", lab0827_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0828", lab0828_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab082b", lab082b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab082c", lab082c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab082d", lab082d_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab082e", lab082e_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab082f", lab082f_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0830", lab0830_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0831", lab0831_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0832", lab0832_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0833", lab0833_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0834", lab0834_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0835", lab0835_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0843", lab0843_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0849", lab0849_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0853", lab0853_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0854", lab0854_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0855", lab0855_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab085b", lab085b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab085c", lab085c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0863", lab0863_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0864", lab0864_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0866", lab0866_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab086c", lab086c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab086d", lab086d_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab086e", lab086e_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab086f", lab086f_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0870", lab0870_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0873", lab0873_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0874", lab0874_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0875", lab0875_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0876", lab0876_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0877", lab0877_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0879", lab0879_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab087a", lab087a_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab087b", lab087b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab087c", lab087c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab087d", lab087d_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab087f", lab087f_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0880", lab0880_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0881", lab0881_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0883", lab0883_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0885", lab0885_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0887", lab0887_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0888", lab0888_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab088b", lab088b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab088f", lab088f_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0890", lab0890_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0893", lab0893_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0894", lab0894_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0895", lab0895_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0896", lab0896_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0898", lab0898_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab089b", lab089b_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab089c", lab089c_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab089d", lab089d_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab089e", lab089e_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a0", lab08a0_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a3", lab08a3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a5", lab08a5_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a6", lab08a6_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a7", lab08a7_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a8", lab08a8_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08a9", lab08a9_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08aa", lab08aa_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08b0", lab08b0_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08b1", lab08b1_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08b2", lab08b2_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08b3", lab08b3_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08b6", lab08b6_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08bc", lab08bc_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab08be", lab08be_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0978", lab0978_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0979", lab0979_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab097a", lab097a_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0f54", lab0f54_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
    { "lab0f57", lab0f57_script, { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
      160, 0, 100, 1 },
};

#define ANIM_REGISTRY_COUNT  162

#endif /* MOON_ANIM_REGISTRY_H */
