/*
 * moon_anim_lab0866.c — IMAGEXCEL animation script "lab0866".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15184
 * (LAB_0866).  40 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0866 — 40 bytes, 1 step(s) */
static const uint8_t lab0866_script[] = {
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0x88, 0x02,  /* frame=0 y=+0 x=-30718 */
    IX_DRAW(0), 0x37, 0x0F, 0x00, 0xFF, 0xFF,  /* frame=55 y=+15 x=-1 */
    IX_DRAW(0), 0x3F, 0xF2, 0x00, 0xFF, 0xE9,  /* frame=63 y=-14 x=-23 */
    IX_DRAW(0), 0x36, 0xF8, 0x00, 0x00, 0x11,  /* frame=54 y=-8 x=+17 */
    IX_DRAW(1), 0x3B, 0x27, 0x00, 0xFF, 0xF5,  /* frame=59 y=+39 x=-11 */
    IX_DRAW(1), 0x2D, 0x24, 0x00, 0x00, 0x0A,  /* frame=45 y=+36 x=+10 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0866_script */
