/*
 * moon_anim_lab081f.c — IMAGEXCEL animation script "lab081f".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14632
 * (LAB_081F).  26 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_081F — 26 bytes, 1 step(s) */
static const uint8_t lab081f_script[] = {
    IX_DRAW(0), 0x02, 0xFB, 0x01, 0xFF, 0xF0,  /* frame=2 y=-5 x=-16 */
    IX_DRAW(0), 0x03, 0x1C, 0x01, 0xFF, 0xE3,  /* frame=3 y=+28 x=-29 */
    IX_DRAW(1), 0x3E, 0xDE, 0x00, 0x00, 0x05,  /* frame=62 y=-34 x=+5 */
    IX_DRAW(1), 0x42, 0x11, 0x20, 0x00, 0x02,  /* frame=66 y=+17 x=+2 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab081f_script */
