/*
 * moon_anim_lab085b.c — IMAGEXCEL animation script "lab085b".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15071
 * (LAB_085B).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_085B — 20 bytes, 1 step(s) */
static const uint8_t lab085b_script[] = {
    IX_DRAW(1), 0x2F, 0xF5, 0x00, 0xFF, 0xEF,  /* frame=47 y=-11 x=-17 */
    IX_DRAW(1), 0x30, 0xF2, 0x00, 0x00, 0x0A,  /* frame=48 y=-14 x=+10 */
    IX_DRAW(0), 0x17, 0xE1, 0x00, 0xFF, 0xDA,  /* frame=23 y=-31 x=-38 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab085b_script */
