/*
 * moon_anim_lab0820.c — IMAGEXCEL animation script "lab0820".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14636
 * (LAB_0820).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0820 — 14 bytes, 1 step(s) */
static const uint8_t lab0820_script[] = {
    IX_DRAW(1), 0x3E, 0xD8, 0x00, 0x00, 0x07,  /* frame=62 y=-40 x=+7 */
    IX_DRAW(0), 0x04, 0xF7, 0x01, 0xFF, 0xF3,  /* frame=4 y=-9 x=-13 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0820_script */
