/*
 * moon_anim_lab00df.c — IMAGEXCEL animation script "lab00df".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2290
 * (LAB_00DF).  38 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00DF — 38 bytes, 2 step(s) */
static const uint8_t lab00df_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x0E, 0x0E, 0x00, 0xFF, 0xAA,  /* frame=14 y=+14 x=-86 */
    IX_DRAW(4), 0x2E, 0x0F, 0x00, 0xFF, 0xB5,  /* frame=46 y=+15 x=-75 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(4), 0x0E, 0x0E, 0x00, 0xFF, 0xAA,  /* frame=14 y=+14 x=-86 */
    IX_DRAW(4), 0x2B, 0x11, 0x00, 0xFF, 0xB5,  /* frame=43 y=+17 x=-75 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab00df_script */
