/*
 * moon_anim_lab07e5.c — IMAGEXCEL animation script "lab07e5".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14003
 * (LAB_07E5).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E5 — 14 bytes, 1 step(s) */
static const uint8_t lab07e5_script[] = {
    IX_DRAW(0), 0x0E, 0xF8, 0x01, 0xFF, 0xF4,  /* frame=14 y=-8 x=-12 */
    IX_DRAW(3), 0x00, 0xF2, 0x00, 0xFF, 0xFB,  /* frame=0 y=-14 x=-5 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e5_script */
