/*
 * moon_anim_lab00e2.c — IMAGEXCEL animation script "lab00e2".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2345
 * (LAB_00E2).  38 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00E2 — 38 bytes, 2 step(s) */
static const uint8_t lab00e2_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x0B, 0x30, 0x00, 0xFF, 0xD7,  /* frame=11 y=+48 x=-41 */
    IX_DRAW(4), 0x2D, 0x2B, 0x00, 0xFF, 0xDD,  /* frame=45 y=+43 x=-35 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(4), 0x0B, 0x30, 0x00, 0xFF, 0xD7,  /* frame=11 y=+48 x=-41 */
    IX_DRAW(4), 0x2C, 0x2C, 0x00, 0xFF, 0xDB,  /* frame=44 y=+44 x=-37 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab00e2_script */
