/*
 * moon_anim_lab07e4.c — IMAGEXCEL animation script "lab07e4".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14000
 * (LAB_07E4).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07E4 — 14 bytes, 1 step(s) */
static const uint8_t lab07e4_script[] = {
    IX_DRAW(3), 0x00, 0xEE, 0x00, 0x00, 0x02,  /* frame=0 y=-18 x=+2 */
    IX_DRAW(0), 0x0D, 0xF8, 0x01, 0xFF, 0xF7,  /* frame=13 y=-8 x=-9 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab07e4_script */
