/*
 * moon_anim_lab0826.c — IMAGEXCEL animation script "lab0826".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14654
 * (LAB_0826).  20 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0826 — 20 bytes, 1 step(s) */
static const uint8_t lab0826_script[] = {
    IX_DRAW(0), 0x0A, 0xFC, 0x01, 0xFF, 0xEC,  /* frame=10 y=-4 x=-20 */
    IX_DRAW(1), 0x3E, 0xD9, 0x00, 0xFF, 0xF4,  /* frame=62 y=-39 x=-12 */
    IX_DRAW(1), 0x42, 0x15, 0x20, 0xFF, 0xF1,  /* frame=66 y=+21 x=-15 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0826_script */
