/*
 * moon_anim_lab0880.c — IMAGEXCEL animation script "lab0880".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15410
 * (LAB_0880).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0880 — 14 bytes, 1 step(s) */
static const uint8_t lab0880_script[] = {
    IX_DRAW(1), 0x07, 0xE6, 0x01, 0xFF, 0xE2,  /* frame=7 y=-26 x=-30 */
    IX_DRAW(1), 0x08, 0x22, 0x01, 0xFF, 0xE2,  /* frame=8 y=+34 x=-30 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0880_script */
