/*
 * moon_anim_lab0855.c — IMAGEXCEL animation script "lab0855".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15034
 * (LAB_0855).  8 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0855 — 8 bytes, 1 step(s) */
static const uint8_t lab0855_script[] = {
    IX_DRAW(0), 0x07, 0xF0, 0x03, 0xFF, 0xF4,  /* frame=7 y=-16 x=-12 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0855_script */
