/*
 * moon_anim_lab00db.c — IMAGEXCEL animation script "lab00db".
 *
 * Auto-generated by tools/extract_scripts.py from program.asm:2240
 * (LAB_00DB).  38 bytes, 2 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_00DB — 38 bytes, 2 step(s) */
static const uint8_t lab00db_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x0F, 0xE6, 0x00, 0xFF, 0xA6,  /* frame=15 y=-26 x=-90 */
    IX_DRAW(4), 0x2F, 0xED, 0x00, 0xFF, 0xAE,  /* frame=47 y=-19 x=-82 */
    IX_STEP_NEXT,  /* end of step 1 */
    0x88, 0x02,
    0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
    IX_DRAW(4), 0x0F, 0xE6, 0x00, 0xFF, 0xA6,  /* frame=15 y=-26 x=-90 */
    IX_DRAW(4), 0x27, 0xEC, 0x00, 0xFF, 0xAE,  /* frame=39 y=-20 x=-82 */
    IX_STEP_SCRIPT_END,  /* end of step 2 */
}; /* lab00db_script */
