/*
 * moon_anim_lab07ff.c — IMAGEXCEL animation script "lab07ff".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14306
 * (LAB_07FF).  68 bytes, 5 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_07FF — 68 bytes, 5 step(s) */
static const uint8_t lab07ff_script[] = {
    0x88, 0x02,
    IX_DRAW(4), 0x3C, 0x09, 0x20, 0xFF, 0xE6,  /* frame=60 y=+9 x=-26 */
    IX_STEP_NEXT,  /* end of step 1 */
    0xA4, 0x12, 0x94, 0x04,
    0x88, 0x02,
    IX_DRAW(4), 0x3D, 0x0B, 0x20, 0xFF, 0xE6,  /* frame=61 y=+11 x=-26 */
    IX_STEP_LOOP,  /* end of step 2 */
    0x88, 0x02,
    IX_DRAW(4), 0x3E, 0x0C, 0x20, 0xFF, 0xE6,  /* frame=62 y=+12 x=-26 */
    IX_STEP_NEXT,  /* end of step 3 */
    0xB0, 0x00,
    IX_DRAW(0), 0x00, 0x00, 0x00, 0xB0, 0x00,  /* frame=0 y=+0 x=-20480 */
    IX_DRAW(0), 0x00, 0x00, 0x00, 0x94, 0x64,  /* frame=0 y=+0 x=-27548 */
    0x88, 0x02,
    IX_DRAW(4), 0x40, 0x18, 0x20, 0xFF, 0xD8,  /* frame=64 y=+24 x=-40 */
    IX_STEP_NEXT,  /* end of step 4 */
    0x88, 0x02,
    IX_DRAW(4), 0x3F, 0x19, 0x20, 0xFF, 0xD7,  /* frame=63 y=+25 x=-41 */
    IX_STEP_SCRIPT_END,  /* end of step 5 */
}; /* lab07ff_script */
