/*
 * moon_anim_lab089b.c — IMAGEXCEL animation script "lab089b".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:15772
 * (LAB_089B).  22 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_089B — 22 bytes, 1 step(s) */
static const uint8_t lab089b_script[] = {
    0x88, 0x02,
    IX_DRAW(0), 0x1F, 0xF6, 0x01, 0xFF, 0xE4,  /* frame=31 y=-10 x=-28 */
    IX_DRAW(0), 0x23, 0x2D, 0x40, 0xFF, 0xDB,  /* frame=35 y=+45 x=-37 */
    IX_DRAW(0), 0x22, 0x39, 0x40, 0xFF, 0xDB,  /* frame=34 y=+57 x=-37 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab089b_script */
