/*
 * moon_anim_anim_08fc_4.c — IMAGEXCEL animation script "anim_08fc_4".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:16573
 * (LAB_0900).  8 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0900 — 8 bytes, 1 step(s) */
static const uint8_t anim_08fc_4_script[] = {
    IX_DRAW(0), 0x25, 0xF7, 0x00, 0xFF, 0xEF,  /* frame=37 y=-9 x=-17 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* anim_08fc_4_script */
