/*
 * moon_anim_lab0809.c — IMAGEXCEL animation script "lab0809".
 *
 * Auto-generated by tools/extract_scripts.py from mog.asm:14365
 * (LAB_0809).  14 bytes, 1 step(s).
 *
 * Macros: IX_DRAW(slot), IX_STEP_NEXT, IX_STEP_LOOP, IX_STEP_SCRIPT_END
 * are defined in tools/imagexcel.h.
 *
 * DO NOT EDIT — re-run tools/extract_scripts.py to regenerate.
 */

#include <stdint.h>
#include "imagexcel.h"

/* LAB_0809 — 14 bytes, 1 step(s) */
static const uint8_t lab0809_script[] = {
    IX_DRAW(1), 0x43, 0xF3, 0x00, 0x00, 0x03,  /* frame=67 y=-13 x=+3 */
    IX_DRAW(0), 0x20, 0xFC, 0x01, 0xFF, 0xF3,  /* frame=32 y=-4 x=-13 */
    IX_STEP_SCRIPT_END,  /* end of step 1 */
}; /* lab0809_script */
